### ISSUE TITLE
--ignore-ssl-errors not working

### ISSUE THREAD

**Issue by thoop** [ariya/phantomjs#12181] opened 2014-04-27 06:36 UTC
I'm having a problem where I'm seeing "SSL handshake failed" only on my AWS EC2 instance, even though I'm using `--ignore-ssl-errors=true`. The weird part is it ONLY happens on my EC2 instance for this one website, and it works locally. I'm also using `--ssl-protocol=tlsv1` and their website is using SNI with AWS Cloudfront. Both my EC2 instance and my local machine are on PhantomJS 1.9.7.

I've tried everything like making sure openssl and ca-certificates are up to date, making sure we have their correct cert, making sure curling their site works, and pointing phantomjs to the certificates directory.

Here's some of my `--debug=true` output:

```
getting https://learni.st
phantom stderr: 2014-04-27T06:18:25 [DEBUG] WebPage - updateLoadingProgress: 10 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] Network - SSL Error: "No error" 
2014-04-27T06:18:25 [DEBUG] Network - SSL Error: "No error" 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] CookieJar - Saved "AWSELB=77C1F30691E24C3635F1BC72711A62B209E042A855CCD8B001F19C9CB6DBDF2F79067F1DA44C89C0961A758EBC0211B52B5FCE241033BBB205D68C8891EAEEC1E94E1F71; domain=learni.st; path=/" 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] WebPage - updateLoadingProgress: 11 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://assets2.learni.st/spa/css/vendor-9e306212.css" 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://assets1.learni.st/spa/css/app-0ee007ab.css" 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://assets1.learni.st/spa/js/app-a16957cd.js" 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://assets2.learni.st/spa/js/vendor-35e66510.js" 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://assets0.learni.st/spa/js/select2.min-16f03230.js" 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://assets3.learni.st/spa/js/templates-11af8771.js" 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] WebPage - updateLoadingProgress: 25 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] WebPage - setupFrame "" 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] WebPage - updateLoadingProgress: 100 

phantom stderr: 2014-04-27T06:18:25 [DEBUG] WebPage - setupFrame ""
...
```

The weird part is the SSL Error: "No error" on the homepage. That page loads just fine and calls `onResourceReceived`, but the subsequent requests don't load and call the `onResourceError` function.

Isn't `--ignore-ssl-errors=true` supposed to keep those SSL handshake errors from happening?

**Comment by adamgotterer** [comment] 2015-01-09 06:03
@saarthakvats  did you ever figure out how to get this to work with https?

**Comment by davidmatas** [comment] 2015-02-09 09:33
I'm also having this problem using phantomas. In OS X works fine without options but in Ubuntu 14.04.1 I've tried all combination with `--ignore-ssl-errors` and `--ssl-protocol` and nothing work :(

```
phantomas --debug --ignore-ssl-errors --ssl-protocol=tlsv3 --analyze-css https://dashboard.socialbro.com
```

```
...
Debug: WebPage - updateLoadingProgress: 14
Debug: Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://dsh-cdn01.socialb.co/public/app/themes/shiro/css/default.css"
...
```

**Comment by Mr0grog** [comment] 2015-03-05 05:53
I’m working on a project that is attempting to track the uptime and availability of various government benefit services (e.g. food assistance programs). In using Phantom to get screenshots of sites when they’re down or having errors, we’ve run into the same problem. No setting for `--ignore-ssl-errors`, `--ssl-protocol`, or `--ssl-ciphers` seems to work.

If it helps, one site that is reliably failing is: https://www.c4yourself.com/c4yourself/index.jsp

**Comment by HelioGuilherme66** [comment] 2015-03-05 14:04
Hi,

It worked for me, with:
C:\Program Files (x86)\phantomjs-1.9.8-windows>.\phantomjs.exe
--ignore-ssl-errors=true --ssl-protocol=any examples\rasterize.js
https://www.c4yourself.com/c4yourself/index.jsp screen.png

(before sending the command, I've set the HTTPS_PROXY environmental
variable with required URL for my net).

Hélio

**Comment by Mr0grog** [comment] 2015-03-07 21:25
@HelioGuilherme66 Maybe it worked because of the proxy? It reliably fails on every network that I’ve tried it, on both OS X, Ubuntu, and Heroku (no proxies being used).

**Comment by Mr0grog** [comment] 2015-03-07 21:31
I should note, also, that SlimerJS handles it just fine. The Chrome and Safari browsers can also load the pages, so I think the issue is definitely with Phantom.

**Comment by VijayalakshmiIyer** [comment] 2015-03-10 11:50
Hi Guys,
I am using PhantomCSS to do a screenshot comparison CSS test. Everytime i run the test i get a blank screenshot. The url is https site. I am pretty new to this and tried everything mentioned above and various other blogs to bypass the SSL, but nothing worked.

My current set up is PhantomJS version 1.9.2 and CasperJS version 1.1.0-DEV. Please advice what should i do.

**Comment by Tomtomgo** [comment] 2015-03-13 16:22
@HelioGuilherme66's solution with `--ssl-protocol=any` worked for me.

**Comment by bgever** [comment] 2015-04-30 03:38
I have the same issue on our build server only (dev machines work fine?).

Our tests run against a local server, where the client-side scripts make calls to a HTTPS (SNI cert) API endpoint. With `--ignore-ssl-errors=true` the calls to the HTTP API fail and our Protractor tests freeze. However, if I pass an invalid value for the `--ssl-protocol=invalid` flag, the tests continue but the API call returns a failed response. This means that the SSL handshake didn't work out. It's the same behavior we see with IE on WinXP, which doesn't support SNI. Relating to the SNI remark by @thoop.

I was able to work around the issue, by replacing the self-signed certificate for localhost with a certificate that uses SHA256 as algorithm, instead of SHA1. [SHA1 algorithm certificates are not trusted by WebKit anymore](https://konklone.com/post/why-google-is-hurrying-the-web-to-kill-sha-1), what forced the use of the `--ignore-ssl-errors=true` flag. With the SHA256 self-signed certificate (also stored in the Trusted Root CA store) this is no longer the case, and we do not need to ignore SSL errors, avoiding the issue.

**Comment by jonny64** [comment] 2015-09-02 20:53
Hi, I don't know why you closed this, guys, but
I have same issue and NO workaround since casperjs is not using phantomjs >= 2

**Comment by sgri** [comment] 2015-11-17 15:42
I have the same issue. 
```
Unable to load resource (#1URL:https://www.popvox.com/bills/us/new)
Error code: 6. Description: SSL handshake failed
```
No flag combination helps.

**Comment by dylotribal** [comment] 2015-12-11 23:38
Same, none of the solutions work on my Ubuntu ec2 instance...   http://stackoverflow.com/questions/12021578/phantomjs-failing-to-open-https-site

**Comment by krthkbharadwaj** [comment] 2015-12-16 15:48
@HelioGuilherme66 : Thanks, that worked for me

**Comment by monolithed** [comment] 2015-12-30 16:38
Have the same problem with 1.9.19 :(

**Comment by OlehHappy** [comment] 2016-03-11 14:57
Same with 2.1.1

**Comment by herlon214** [comment] 2016-09-27 14:55
--ignore-ssl-errors=true --ssl-protocol=any worked for me

**Comment by Vitallium** [comment] 2017-01-11 20:42
Fixed in 2.5 beta

**Closed by Vitallium** 2017-01-11 20:42 UTC
Labels: Fixed in dev

**Comment by arunchandramouli** [comment] 2017-01-16 14:05
I am using python and phantomjs driver to crawl google careers - https://www.careers.google.com
I tried in the service_args = ['--ignore-ssl-errors=yes','--ignore-ssl-errors=true','--ssl-protocl=any']
Phantomjs version 2.0.0

**Comment by arunchandramouli** [comment] 2017-01-16 14:06
But it always renders about:blank

**Comment by cardiner** [comment] 2017-02-20 09:59
Having the same problem as @arunchandramouli. phantomjs --ignore-ssl-errors=true --ssl-protocol=any --debug=true but renders blank page. Works fine on dev environment where ssl is not enabled. production servers renders blank pages

debug output.

2017-02-20T09:39:06 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://mysite.com/image_placeholders?page_uuid=03aaa2ee-7f16-4fa2-8609-20bcb50576c1"

**Comment by amarynets** [comment] 2017-03-20 12:40
I have the same problem as @cardiner and @arunchandramouli 
I use this way for configure PhantomJS for my Python code:
`webdriver.DesiredCapabilities.PHANTOMJS['phantomjs.page.settings.userAgent'] = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'
        
webdriver.DesiredCapabilities.PHANTOMJS['phantomjs.page.settings.load-images'] = True
        webdriver.DesiredCapabilities.PHANTOMJS['phantomjs.page.settings.ignore-ssl-errors'] = True
        webdriver.DesiredCapabilities.PHANTOMJS['phantomjs.page.settings.ssl-protocl'] = 'any'`

**Comment by shubhamj-cuelogic** [comment] 2017-05-25 08:25
I am facing the same issue. Below code working fine in windows where it is also executing the https but in Ubuntu I am getting same error for https.  it is working fine for http

I am using the below code 

DesiredCapabilities capabilities = null;
		ArrayList<String> cliArgsCap = new ArrayList<String>();
		capabilities = DesiredCapabilities.phantomjs();
		cliArgsCap.add("--web-security=false");
		cliArgsCap.add("--ssl-protocol=any");
		cliArgsCap.add("--ignore-ssl-errors=true");
		capabilities.setCapability("takesScreenshot", true);
		capabilities.setJavascriptEnabled(true);
		capabilities.setCapability(
		    PhantomJSDriverService.PHANTOMJS_CLI_ARGS, cliArgsCap);
		capabilities.setCapability(
		    PhantomJSDriverService.PHANTOMJS_GHOSTDRIVER_CLI_ARGS,
		        new String[] { "--logLevel=2" });

**Comment by luispeerez** [comment] 2017-09-22 21:06
Same here, getting the SSL handshake error using the 2.1.15 version. I am using

--ignore-ssl-errors=true --ssl-protocol=any

**Comment by verishal** [comment] 2017-10-13 11:28
I am using angular js and phantomjs driver to crawl google careers - https://example.com
I tried in the service_args = ['--ignore-ssl-errors=yes','--ignore-ssl-errors=true','--ssl-protocl=any']
Phantomjs version 2.1.1.
 I tried in the service_args ,but is same ssl error. google  crawl not accept the https://example.com/?_escaped_fragment_= request,In https but it still working in http.
please help me...
when i request the service_args:

        phantomjs --disk-cache=no  --ignore-ssl-errors=yes --ignore-ssl-errors=true --ssl-protocol=any /opt/bitnami/apache-tomcat/stt/ROOT/js/angular-seo.js 9090 https://example.com/

**Comment by luispeerez** [comment] 2017-10-13 18:32
I had problems with this, unti I figured it out that my SSL Certificate from Comodo was wrongly configured, I followed this tutorial https://www.namecheap.com/support/knowledgebase/article.aspx/9419//installing-a-certificate-on-nginx and now it works ok :)

**Comment by verishal** [comment] 2017-10-27 05:55
Hello luispeerez. I followed this tutorial https://www.namecheap.com/support/knowledgebase/article.aspx/9419//installing-a-certificate-on-nginx .but not working .

**Comment by luispeerez** [comment] 2017-11-03 17:04
@verishal your certificate is from comodo?

**Comment by verishal** [comment] 2017-11-04 04:42
No.because I get certificate from SSL4.

**Comment by sfantu** [comment] 2017-11-05 02:36
Also facing this problem.
The page is blank.

**Comment by verishal** [comment] 2017-11-06 04:23
sfantu.Do you have some idea?

**Comment by Naveenkv93** [comment] 2017-12-07 09:44
Page is navigating to about:blank. Tried all the combination mentioned above with SSL, but nothing worked.

**Comment by pushplataranjan** [comment] 2022-04-11 17:56
phantomjs --web-security=false --ignore-ssl-errors=true scripts.js

**Comment by verishal** [comment] 2022-04-11 17:59
Thanks for solving this issue.i have resolved the issue.last 2 years
