### ISSUE TITLE
Crash dump

### ISSUE THREAD

**Issue by httpways** [ariya/phantomjs#13585] opened 2015-09-14 07:35 UTC
Hi,

I have some crashes on linux, here is the stack trace:

Operating system: Linux
                  0.0.0 Linux 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64
CPU: amd64
     family 6 model 69 stepping 1
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0x110

Thread 0 (crashed)
 0  phantomjs + 0x696bba
    rbx = 0x0000000000000000   r12 = 0x0000000000000100
    r13 = 0x00007f7c392b6118   r14 = 0x00007fffd75cd900
    r15 = 0x0000000000000000   rip = 0x0000000000a96bba
    rsp = 0x00007fffd75cd410   rbp = 0x00007fffd75cd440
    Found by: given as instruction pointer in context
 1  phantomjs + 0x69ac3c
    rip = 0x0000000000a9ac3d   rsp = 0x00007fffd75cd440
    rbp = 0x00007fffd75cd440
    Found by: stack scanning
 2  phantomjs + 0x4edc74
    rip = 0x00000000008edc75   rsp = 0x00007fffd75cd480
    Found by: stack scanning
 3  phantomjs + 0x4f37b2
    rip = 0x00000000008f37b3   rsp = 0x00007fffd75cd4e0
    Found by: stack scanning
 4  phantomjs + 0x107e84f
    rip = 0x000000000147e850   rsp = 0x00007fffd75cd590
    Found by: stack scanning
 5  phantomjs + 0xd6e9d3
    rip = 0x000000000116e9d4   rsp = 0x00007fffd75cd5d0
    Found by: stack scanning
 6  phantomjs + 0xd6ed50
    rip = 0x000000000116ed51   rsp = 0x00007fffd75cd5e0
    Found by: stack scanning
 7  phantomjs + 0x5ef67b
    rip = 0x00000000009ef67c   rsp = 0x00007fffd75cd640
    Found by: stack scanning
 8  phantomjs + 0x5d546e
    rip = 0x00000000009d546f   rsp = 0x00007fffd75cd6c0
    Found by: stack scanning
 9  phantomjs + 0x5da672
    rip = 0x00000000009da673   rsp = 0x00007fffd75cd710
    Found by: stack scanning
10  phantomjs + 0xe0b3f
    rip = 0x00000000004e0b40   rsp = 0x00007fffd75cd780
    Found by: stack scanning
11  phantomjs + 0x5b919c
    rip = 0x00000000009b919d   rsp = 0x00007fffd75cd850
    Found by: stack scanning
12  phantomjs + 0x5d313f
    rip = 0x00000000009d3140   rsp = 0x00007fffd75cd860
    Found by: stack scanning
13  phantomjs + 0x5d91a0
    rip = 0x00000000009d91a1   rsp = 0x00007fffd75cd930
    Found by: stack scanning
14  phantomjs + 0x5d546e
    rip = 0x00000000009d546f   rsp = 0x00007fffd75cd940
    Found by: stack scanning
15  phantomjs + 0x5db251
    rip = 0x00000000009db252   rsp = 0x00007fffd75cd990
    Found by: stack scanning

Thread 1
 0  libc-2.19.so + 0xc0f3d
    rbx = 0x00007f7c8cc39c80   r12 = 0x00007f7c8cc39d00
    r13 = 0x0000000000000000   r14 = 0x00007f7c8cc3a9c0
    r15 = 0x00007f7c8cc3a700   rip = 0x00007f7c8df23f3d
    rsp = 0x00007f7c8cc39c60   rbp = 0x00000000ffffffff
    Found by: given as instruction pointer in context
 1  libc-2.19.so + 0xc0dd3
    rip = 0x00007f7c8df23dd4   rsp = 0x00007f7c8cc39c70
    Found by: stack scanning
 2  phantomjs + 0x2e2c
    rip = 0x0000000000402e2d   rsp = 0x00007f7c8cc39d10
    Found by: stack scanning
 3  ld-2.19.so + 0xa990
    rip = 0x00007f7c8f55b991   rsp = 0x00007f7c8cc39d20
    Found by: stack scanning
 4  libc-2.19.so + 0xe89f
    rip = 0x00007f7c8de718a0   rsp = 0x00007f7c8cc39d28
    Found by: stack scanning
 5  phantomjs + 0x18b5d6f
    rip = 0x0000000001cb5d70   rsp = 0x00007f7c8cc39d88
    Found by: stack scanning
 6  libc-2.19.so + 0x3d27
    rip = 0x00007f7c8de66d28   rsp = 0x00007f7c8cc39d98
    Found by: stack scanning
 7  libc-2.19.so + 0xe89f
    rip = 0x00007f7c8de718a0   rsp = 0x00007f7c8cc39da8
    Found by: stack scanning
 8  phantomjs + 0x173d7
    rip = 0x00000000004173d8   rsp = 0x00007f7c8cc39db0
    Found by: stack scanning
 9  phantomjs + 0x2e2c
    rip = 0x0000000000402e2d   rsp = 0x00007f7c8cc39de0
    Found by: stack scanning
10  libc-2.19.so + 0x10d77
    rip = 0x00007f7c8de73d78   rsp = 0x00007f7c8cc39de8
    Found by: stack scanning
11  phantomjs + 0x24c7
    rip = 0x00000000004024c8   rsp = 0x00007f7c8cc39df0
    Found by: stack scanning
12  libpthread-2.19.so + 0x1033f
    rip = 0x00007f7c8ea58340   rsp = 0x00007f7c8cc39e18
    Found by: stack scanning
13  libpthread-2.19.so + 0xc4a3
    rip = 0x00007f7c8ea544a4   rsp = 0x00007f7c8cc39e20
    Found by: stack scanning
14  phantomjs + 0xddb2d
    rip = 0x00000000004ddb2e   rsp = 0x00007f7c8cc39e50
    Found by: stack scanning
15  libc-2.19.so + 0x991f
    rip = 0x00007f7c8de6c920   rsp = 0x00007f7c8cc39e70
    Found by: stack scanning
16  phantomjs + 0xddd98
    rip = 0x00000000004ddd99   rsp = 0x00007f7c8cc39ed0
    Found by: stack scanning
17  libpthread-2.19.so + 0x8181
    rip = 0x00007f7c8ea50182   rsp = 0x00007f7c8cc39ee0
    Found by: stack scanning
18  libc-2.19.so + 0xfa47c
    rip = 0x00007f7c8df5d47d   rsp = 0x00007f7c8cc39f80
    Found by: stack scanning

Thread 2
 0  libc-2.19.so + 0xf1da3
    rbx = 0x0000000000000000   r12 = 0x00007f7c8c438db0
    r13 = 0x000000000000000c   r14 = 0x00007f7c84000a98
    r15 = 0x00007f7c84000d30   rip = 0x00007f7c8df54da3
    rsp = 0x00007f7c8c438b80   rbp = 0x00007f7c840008e0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906426
    rip = 0x0000000001d06427   rsp = 0x00007f7c8c438b90
    Found by: stack scanning
 2  ld-2.19.so + 0x9e9b
    rip = 0x00007f7c8f55ae9c   rsp = 0x00007f7c8c438be0
    Found by: stack scanning
 3  phantomjs + 0x19076e6
    rip = 0x0000000001d076e7   rsp = 0x00007f7c8c438c20
    Found by: stack scanning
 4  phantomjs + 0x18f6bb6
    rip = 0x0000000001cf6bb7   rsp = 0x00007f7c8c438c40
    Found by: stack scanning
 5  phantomjs + 0x1801ac2
    rip = 0x0000000001c01ac3   rsp = 0x00007f7c8c438c50
    Found by: stack scanning
 6  libc-2.19.so + 0x10892c
    rip = 0x00007f7c8df6b92d   rsp = 0x00007f7c8c438c90
    Found by: stack scanning
 7  phantomjs + 0x1840c73
    rip = 0x0000000001c40c74   rsp = 0x00007f7c8c438ca0
    Found by: stack scanning
 8  phantomjs + 0x1840b78
    rip = 0x0000000001c40b79   rsp = 0x00007f7c8c438ce0
    Found by: stack scanning
 9  phantomjs + 0x19070a5
    rip = 0x0000000001d070a6   rsp = 0x00007f7c8c438cf0
    Found by: stack scanning
10  phantomjs + 0x1908191
    rip = 0x0000000001d08192   rsp = 0x00007f7c8c438d60
    Found by: stack scanning
11  phantomjs + 0x18dd5b4
    rip = 0x0000000001cdd5b5   rsp = 0x00007f7c8c438db0
    Found by: stack scanning
12  phantomjs + 0x18ddda8
    rip = 0x0000000001cddda9   rsp = 0x00007f7c8c438dc0
    Found by: stack scanning
13  phantomjs + 0x18dda17
    rip = 0x0000000001cdda18   rsp = 0x00007f7c8c438de0
    Found by: stack scanning
14  phantomjs + 0x17dfef5
    rip = 0x0000000001bdfef6   rsp = 0x00007f7c8c438e40
    Found by: stack scanning
15  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007f7c8c438e90
    Found by: stack scanning
16  libpthread-2.19.so + 0x8181
    rip = 0x00007f7c8ea50182   rsp = 0x00007f7c8c438ee0
    Found by: stack scanning
17  libc-2.19.so + 0xfa47c
    rip = 0x00007f7c8df5d47d   rsp = 0x00007f7c8c438f80
    Found by: stack scanning

Thread 3
 0  libc-2.19.so + 0xf1da3
    rbx = 0x00007f7c8ab17d60   r12 = 0x000000000003b880
    r13 = 0x0000000000000039   r14 = 0x00007f7c3c000a98
    r15 = 0x00007f7c3c000d30   rip = 0x00007f7c8df54da3
    rsp = 0x00007f7c8ab17b80   rbp = 0x0000000000070a12
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906327
    rip = 0x0000000001d06328   rsp = 0x00007f7c8ab17b90
    Found by: stack scanning
 2  phantomjs + 0x19076e6
    rip = 0x0000000001d076e7   rsp = 0x00007f7c8ab17c20
    Found by: stack scanning
 3  phantomjs + 0x18f6bb6
    rip = 0x0000000001cf6bb7   rsp = 0x00007f7c8ab17c40
    Found by: stack scanning
 4  phantomjs + 0x1801af3
    rip = 0x0000000001c01af4   rsp = 0x00007f7c8ab17c50
    Found by: stack scanning
 5  libc-2.19.so + 0x10892c
    rip = 0x00007f7c8df6b92d   rsp = 0x00007f7c8ab17c90
    Found by: stack scanning
 6  phantomjs + 0x1840c73
    rip = 0x0000000001c40c74   rsp = 0x00007f7c8ab17ca0
    Found by: stack scanning
 7  phantomjs + 0x1907ded
    rip = 0x0000000001d07dee   rsp = 0x00007f7c8ab17cd0
    Found by: stack scanning
 8  phantomjs + 0x1840b78
    rip = 0x0000000001c40b79   rsp = 0x00007f7c8ab17ce0
    Found by: stack scanning
 9  phantomjs + 0x19070a5
    rip = 0x0000000001d070a6   rsp = 0x00007f7c8ab17cf0
    Found by: stack scanning
10  phantomjs + 0x1908191
    rip = 0x0000000001d08192   rsp = 0x00007f7c8ab17d60
    Found by: stack scanning
11  phantomjs + 0x18dd5b4
    rip = 0x0000000001cdd5b5   rsp = 0x00007f7c8ab17db0
    Found by: stack scanning
12  phantomjs + 0x18ddda8
    rip = 0x0000000001cddda9   rsp = 0x00007f7c8ab17dc0
    Found by: stack scanning
13  phantomjs + 0x18dda17
    rip = 0x0000000001cdda18   rsp = 0x00007f7c8ab17de0
    Found by: stack scanning
14  phantomjs + 0x17dfef5
    rip = 0x0000000001bdfef6   rsp = 0x00007f7c8ab17e40
    Found by: stack scanning
15  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007f7c8ab17e90
    Found by: stack scanning
16  libpthread-2.19.so + 0x8181
    rip = 0x00007f7c8ea50182   rsp = 0x00007f7c8ab17ee0
    Found by: stack scanning
17  libc-2.19.so + 0xfa47c
    rip = 0x00007f7c8df5d47d   rsp = 0x00007f7c8ab17f80
    Found by: stack scanning

Thread 4
 0  libpthread-2.19.so + 0xc7ce
    rbx = 0x00007f7c3c005350   r12 = 0x000000000000002f
    r13 = 0x00007f7c8a316df0   r14 = 0xffffffffffffff92
    r15 = 0x00007f7c3c005200   rip = 0x00007f7c8ea547ce
    rsp = 0x00007f7c8a316d70   rbp = 0x00007f7c3c005640
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e3ad6
    rip = 0x0000000001be3ad7   rsp = 0x00007f7c8a316dd0
    Found by: stack scanning
 2  phantomjs + 0x17d793c
    rip = 0x0000000001bd793d   rsp = 0x00007f7c8a316e50
    Found by: stack scanning
 3  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007f7c8a316e90
    Found by: stack scanning
 4  libpthread-2.19.so + 0x8181
    rip = 0x00007f7c8ea50182   rsp = 0x00007f7c8a316ee0
    Found by: stack scanning
 5  libc-2.19.so + 0xfa47c
    rip = 0x00007f7c8df5d47d   rsp = 0x00007f7c8a316f80
    Found by: stack scanning

Thread 5
 0  libpthread-2.19.so + 0xc414
    rbx = 0x000000000387cfa0   r12 = 0x004189374bc6a7ef
    r13 = 0xffffffffffffffff   r14 = 0x000000000387cfc8
    r15 = 0x000000000387ddc0   rip = 0x00007f7c8ea54414
    rsp = 0x00007f7c89838d40   rbp = 0x00007f7c8b13d050
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e3af4
    rip = 0x0000000001be3af5   rsp = 0x00007f7c89838d70
    rbp = 0x00007f7c8b13d050
    Found by: stack scanning
 2  phantomjs + 0xe71e9
    rip = 0x00000000004e71ea   rsp = 0x00007f7c89838df0
    rbp = 0x00007f7c8b13d050
    Found by: stack scanning
 3  phantomjs + 0xd85368
    rip = 0x0000000001185369   rsp = 0x00007f7c89838e10
    rbp = 0x00007f7c8b13d050
    Found by: stack scanning
 4  phantomjs + 0xd85592
    rip = 0x0000000001185593   rsp = 0x00007f7c89838e50
    rbp = 0x00007f7c8b13d050
    Found by: stack scanning
 5  phantomjs + 0xe69fa
    rip = 0x00000000004e69fb   rsp = 0x00007f7c89838e80
    rbp = 0x00007f7c8b13d050
    Found by: stack scanning
 6  phantomjs + 0x17e2dc1
    rip = 0x0000000001be2dc2   rsp = 0x00007f7c89838e90
    rbp = 0x00007f7c8b13d050
    Found by: stack scanning
 7  libpthread-2.19.so + 0x8181
    rip = 0x00007f7c8ea50182   rsp = 0x00007f7c89838ee0
    rbp = 0x00007f7c8b13d050
    Found by: stack scanning
 8  libc-2.19.so + 0xfa47c
    rip = 0x00007f7c8df5d47d   rsp = 0x00007f7c89838f80
    rbp = 0x00007f7c8b13d050
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x7f7c39ad6000 - 0x7f7c39b75fff  DejaVuSansCondensed-Bold.ttf  ???
0x7f7c39b76000 - 0x7f7c39b8cfff  z003034l.pfb  ???
0x7f7c39b8d000 - 0x7f7c39b95fff  s050000l.pfb  ???
0x7f7c39b96000 - 0x7f7c39ba1fff  d050000l.pfb  ???
0x7f7c39ba2000 - 0x7f7c39bbdfff  Saab.ttf  ???
0x7f7c39bbe000 - 0x7f7c39be4fff  utkal.ttf  ???
0x7f7c39be5000 - 0x7f7c39bf5fff  lohit_hi.ttf  ???
0x7f7c39bf6000 - 0x7f7c39c07fff  gargi.ttf  ???
0x7f7c39c08000 - 0x7f7c39c38fff  Vemana.ttf  ???
0x7f7c39c39000 - 0x7f7c39c4dfff  Rekha.ttf  ???
0x7f7c39c4e000 - 0x7f7c39cabfff  Rachana_04.ttf  ???
0x7f7c39cac000 - 0x7f7c39cdbfff  Pothana2000.ttf  ???
0x7f7c39cdc000 - 0x7f7c39cf9fff  Malige-n.ttf  ???
0x7f7c39cfa000 - 0x7f7c39d12fff  Kedage-n.ttf  ???
0x7f7c39d13000 - 0x7f7c39d29fff  TlwgTypo.ttf  ???
0x7f7c39d2a000 - 0x7f7c39d40fff  TlwgTypist.ttf  ???
0x7f7c39d41000 - 0x7f7c39d58fff  TlwgTypewriter.ttf  ???
0x7f7c39d59000 - 0x7f7c39d6ffff  TlwgMono.ttf  ???
0x7f7c39d70000 - 0x7f7c39de4fff  Padauk-book.ttf  ???
0x7f7c39de5000 - 0x7f7c39e58fff  Padauk.ttf  ???
0x7f7c39e59000 - 0x7f7c39e8afff  opens___.ttf  ???
0x7f7c39e8b000 - 0x7f7c3a22cfff  NanumMyeongjo.ttf  ???
0x7f7c3a22d000 - 0x7f7c3a62afff  NanumBarunGothic.ttf  ???
0x7f7c3a62b000 - 0x7f7c3a637fff  KacstOne.ttf  ???
0x7f7c3a638000 - 0x7f7c3a656fff  mry_KacstQurn.ttf  ???
0x7f7c3a657000 - 0x7f7c3a674fff  KacstTitleL.ttf  ???
0x7f7c3a675000 - 0x7f7c3a685fff  KacstTitle.ttf  ???
0x7f7c3a686000 - 0x7f7c3a690fff  KacstScreen.ttf  ???
0x7f7c3a691000 - 0x7f7c3a6a2fff  KacstQurn.ttf  ???
0x7f7c3a6a3000 - 0x7f7c3a6adfff  KacstPoster.ttf  ???
0x7f7c3a6ae000 - 0x7f7c3a6bbfff  KacstPen.ttf  ???
0x7f7c3a6bc000 - 0x7f7c3a6cdfff  KacstOffice.ttf  ???
0x7f7c3a6ce000 - 0x7f7c3a6defff  KacstNaskh.ttf  ???
0x7f7c3a6df000 - 0x7f7c3a6ecfff  KacstLetter.ttf  ???
0x7f7c3a6ed000 - 0x7f7c3a6fbfff  KacstFarsi.ttf  ???
0x7f7c3a6fc000 - 0x7f7c3a705fff  KacstDigital.ttf  ???
0x7f7c3a706000 - 0x7f7c3a711fff  KacstDecorative.ttf  ???
0x7f7c3a712000 - 0x7f7c3a721fff  KacstBook.ttf  ???
0x7f7c3a722000 - 0x7f7c3a72efff  KacstArt.ttf  ???
0x7f7c3a72f000 - 0x7f7c3a737fff  DroidSansThai.ttf  ???
0x7f7c3a738000 - 0x7f7c3a856fff  DroidSansJapanese.ttf  ???
0x7f7c3a857000 - 0x7f7c3a85efff  DroidSansHebrew-Regular.ttf  ???
0x7f7c3a85f000 - 0x7f7c3a864fff  DroidSansGeorgian.ttf  ???
0x7f7c3a865000 - 0x7f7c3a89cfff  DroidSansEthiopic-Regular.ttf  ???
0x7f7c3a89d000 - 0x7f7c3a8a0fff  DroidSansArmenian.ttf  ???
0x7f7c3a8a1000 - 0x7f7c3a8b6fff  DroidNaskh-Regular.ttf  ???
0x7f7c3a8b7000 - 0x7f7c3a8c0fff  Symbol.pfb  ???
0x7f7c3a8c1000 - 0x7f7c3aeb3fff  TakaoPGothic.ttf  ???
0x7f7c3aeb4000 - 0x7f7c3aebcfff  octicons-regular.ttf  ???
0x7f7c3aebd000 - 0x7f7c3aed0fff  fontawesome-regular.ttf  ???
0x7f7c3aed1000 - 0x7f7c3aeebfff  p052003l.pfb  ???
0x7f7c3aeec000 - 0x7f7c3af03fff  n022003l.pfb  ???
0x7f7c3af04000 - 0x7f7c3af1cfff  n021003l.pfb  ???
0x7f7c3af1d000 - 0x7f7c3af36fff  c059013l.pfb  ???
0x7f7c3af37000 - 0x7f7c3af4ffff  b018012l.pfb  ???
0x7f7c3af50000 - 0x7f7c3af5ffff  a010015l.pfb  ???
0x7f7c3af60000 - 0x7f7c3af92fff  UbuntuMono-R.ttf  ???
0x7f7c3af93000 - 0x7f7c3afe8fff  Ubuntu-C.ttf  ???
0x7f7c3afe9000 - 0x7f7c3b028fff  Ubuntu-M.ttf  ???
0x7f7c3b029000 - 0x7f7c3b069fff  KhmerOSsys.ttf  ???
0x7f7c3b06a000 - 0x7f7c3b078fff  VeraSe.ttf  ???
0x7f7c3b079000 - 0x7f7c3b085fff  VeraMono.ttf  ???
0x7f7c3b086000 - 0x7f7c3b09afff  Sawasdee.ttf  ???
0x7f7c3b09b000 - 0x7f7c3b0c1fff  Purisa.ttf  ???
0x7f7c3b0c2000 - 0x7f7c3b0dbfff  Norasi.ttf  ???
0x7f7c3b0dc000 - 0x7f7c3b0f0fff  Kinnari.ttf  ???
0x7f7c3b0f1000 - 0x7f7c3b53efff  TibetanMachineUni.ttf  ???
0x7f7c3b53f000 - 0x7f7c3b564fff  LiberationSerif-Regular.ttf  ???
0x7f7c3b565000 - 0x7f7c3b580fff  LiberationSansNarrow-Regular.ttf  ???
0x7f7c3b581000 - 0x7f7c3b5a3fff  LiberationSans-Regular.ttf  ???
0x7f7c3b5a4000 - 0x7f7c3b5befff  LiberationMono-Regular.ttf  ???
0x7f7c3b5bf000 - 0x7f7c3b5d5fff  Phetsarath_OT.ttf  ???
0x7f7c3b5d6000 - 0x7f7c3b8fcfff  FreeSerif.ttf  ???
0x7f7c3b8fd000 - 0x7f7c3b98dfff  FreeMono.ttf  ???
0x7f7c3b98e000 - 0x7f7c3b9b8fff  DroidSerif-Regular.ttf  ???
0x7f7c3b9b9000 - 0x7f7c3b9d6fff  DroidSansMono.ttf  ???
0x7f7c3b9d7000 - 0x7f7c3ba05fff  DroidSans.ttf  ???
0x7f7c3ba06000 - 0x7f7c3ba57fff  DejaVuSerifCondensed.ttf  ???
0x7f7c3ba58000 - 0x7f7c3baa9fff  DejaVuSansMono.ttf  ???
0x7f7c3baaa000 - 0x7f7c3bb37fff  AbyssinicaSIL-R.ttf  ???
0x7f7c3bb38000 - 0x7f7c3bb45fff  Cantarell-Regular.otf  ???
0x7f7c3bb46000 - 0x7f7c3bb4efff  c0648bt_.pfb  ???
0x7f7c3bb4f000 - 0x7f7c3bb88fff  SourceCodePro+Powerline+Awesome+Regular.ttf  ???
0x7f7c3bb89000 - 0x7f7c3bbdafff  PragmataPro.ttf  ???
0x7f7c3bbdb000 - 0x7f7c3bffffff  NanumGothic.ttf  ???
0x7f7c88002000 - 0x7f7c8800bfff  c0419bt_.pfb  ???
0x7f7c8800c000 - 0x7f7c8802ffff  Inconsolata+Awesome.ttf  ???
0x7f7c88030000 - 0x7f7c88068fff  Droid+Sans+Mono+Awesome.ttf  ???
0x7f7c88069000 - 0x7f7c881e6fff  FreeSans.ttf  ???
0x7f7c881e7000 - 0x7f7c88231fff  lklug.ttf  ???
0x7f7c88232000 - 0x7f7c88283fff  Meera_04.ttf  ???
0x7f7c88284000 - 0x7f7c88294fff  lohit_ta.ttf  ???
0x7f7c88295000 - 0x7f7c8829bfff  lohit_pa.ttf  ???
0x7f7c8829c000 - 0x7f7c882abfff  lohit_gu.ttf  ???
0x7f7c882ac000 - 0x7f7c882cefff  lohit_bn.ttf  ???
0x7f7c882cf000 - 0x7f7c882fcfff  MuktiNarrow.ttf  ???
0x7f7c882fd000 - 0x7f7c8833dfff  KhmerOS.ttf  ???
0x7f7c8833e000 - 0x7f7c8878ffff  DroidSansFallbackFull.ttf  ???
0x7f7c88790000 - 0x7f7c887a3fff  Umpush.ttf  ???
0x7f7c887a4000 - 0x7f7c887b6fff  Garuda.ttf  ???
0x7f7c887b7000 - 0x7f7c887cafff  Loma.ttf  ???
0x7f7c887cb000 - 0x7f7c887e0fff  Waree.ttf  ???
0x7f7c887e1000 - 0x7f7c887f1fff  Vera.ttf  ???
0x7f7c8899c000 - 0x7f7c889affff  n019003l.pfb  ???
0x7f7c889b0000 - 0x7f7c88a65fff  DejaVuSans.ttf  ???
0x7f7c8902f000 - 0x7f7c89031fff  pomicons-regular.ttf  ???
0x7f7c898aa000 - 0x7f7c898defff  hosts  ???
0x7f7c898df000 - 0x7f7c89af7fff  libresolv-2.19.so  ???
0x7f7c8cc3b000 - 0x7f7c8ce99fff  libssl.so.1.0.0  ???
0x7f7c8ce9a000 - 0x7f7c8d270fff  libcrypto.so.1.0.0  ???
0x7f7c8d275000 - 0x7f7c8d7f9fff  locale-archive  ???
0x7f7c8d7fa000 - 0x7f7c8da23fff  libexpat.so.1.6.0  ???
0x7f7c8da24000 - 0x7f7c8dc49fff  libpng12.so.0.50.0  ???
0x7f7c8dc4a000 - 0x7f7c8de62fff  libz.so.1.2.8  ???
0x7f7c8de63000 - 0x7f7c8e222fff  libc-2.19.so  ???
0x7f7c8e228000 - 0x7f7c8e43dfff  libgcc_s.so.1  ???
0x7f7c8e43e000 - 0x7f7c8e743fff  libm-2.19.so  ???
0x7f7c8e744000 - 0x7f7c8ea32fff  libstdc++.so.6.0.19  ???
0x7f7c8ea48000 - 0x7f7c8ec61fff  libpthread-2.19.so  ???
0x7f7c8ec66000 - 0x7f7c8ee6dfff  librt-2.19.so  ???
0x7f7c8ee6e000 - 0x7f7c8f071fff  libdl-2.19.so  ???
0x7f7c8f072000 - 0x7f7c8f2adfff  libfontconfig.so.1.8.0  ???
0x7f7c8f2ae000 - 0x7f7c8f550fff  libfreetype.so.6.11.1  ???
0x7f7c8f551000 - 0x7f7c8f573fff  ld-2.19.so  ???
0x7f7c8f575000 - 0x7f7c8f575fff  PowerlineSymbols.otf  ???
0x7f7c8f6a9000 - 0x7f7c8f6affff  gconv-modules.cache  ???
0x7f7c8f6b0000 - 0x7f7c8f6d5fff  libc.mo  ???
0x7f7c8f6d6000 - 0x7f7c8f6d6fff  c05880de57d1f5e948fdfacc138775d9-le64.cache-4  ???
0x7f7c8f6d7000 - 0x7f7c8f6e1fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-4  ???
0x7f7c8f6e2000 - 0x7f7c8f6e3fff  99e8ed0e538f840c565b6ed5dad60d56-le64.cache-4  ???
0x7f7c8f6e4000 - 0x7f7c8f6e9fff  2cd17615ca594fa2959ae173292e504c-le64.cache-4  ???
0x7f7c8f6ea000 - 0x7f7c8f6eafff  e7071f4a29fa870f4323321c154eba04-le64.cache-4  ???
0x7f7c8f6eb000 - 0x7f7c8f6ebfff  0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-4  ???
0x7f7c8f6ec000 - 0x7f7c8f6f2fff  a755afe4a08bf5b97852ceb7400b47bc-le64.cache-4  ???
0x7f7c8f6f3000 - 0x7f7c8f6fefff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-4  ???
0x7f7c8f6ff000 - 0x7f7c8f702fff  de156ccd2eddbdc19d37a45b8b2aac9c-le64.cache-4  ???
0x7f7c8f703000 - 0x7f7c8f716fff  04aabc0a78ac019cf9454389977116d2-le64.cache-4  ???
0x7f7c8f717000 - 0x7f7c8f717fff  1ac9eb803944fde146138c791f5cc56a-le64.cache-4  ???
0x7f7c8f718000 - 0x7f7c8f71bfff  385c0604a188198f04d133e54aba7fe7-le64.cache-4  ???
0x7f7c8f71c000 - 0x7f7c8f71cfff  dc05db6664285cc2f12bf69c139ae4c3-le64.cache-4  ???
0x7f7c8f71d000 - 0x7f7c8f721fff  8801497958630a81b71ace7c5f9b32a8-le64.cache-4  ???
0x7f7c8f722000 - 0x7f7c8f728fff  3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-4  ???
0x7f7c8f729000 - 0x7f7c8f72efff  b47c4e1ecd0709278f4910c18777a504-le64.cache-4  ???
0x7f7c8f72f000 - 0x7f7c8f741fff  d52a8644073d54c13679302ca1180695-le64.cache-4  ???
0x7f7c8f742000 - 0x7f7c8f74afff  3f7329c5293ffd510edef78f73874cfd-le64.cache-4  ???
0x7f7c8f754000 - 0x7f7c8f755fff  767a8244fc0220cfb567a839d0392e0b-le64.cache-4  ???
0x7f7c8f756000 - 0x7f7c8f756fff  4794a0821666d79190d59a36cb4f44b5-le64.cache-4  ???
0x7f7c8f757000 - 0x7f7c8f757fff  56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-4  ???
0x7f7c8f758000 - 0x7f7c8f758fff  b9d506c9ac06c20b433354fa67a72993-le64.cache-4  ???
0x7f7c8f759000 - 0x7f7c8f763fff  d589a48862398ed80a3d6066f4f56f4c-le64.cache-4  ???
0x7f7c8f764000 - 0x7f7c8f764fff  0c9eb80ebd1c36541ebe2852d3bb0c49-le64.cache-4  ???
0x7f7c8f765000 - 0x7f7c8f765fff  62f91419b9ebdb6975e7e41ab6412357-le64.cache-4  ???
0x7f7c8f766000 - 0x7f7c8f768fff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-4  ???
0x7f7c8f769000 - 0x7f7c8f76cfff  7ef2298fde41cc6eeb7af42e48b7d293-le64.cache-4  ???
0x7f7c8f76d000 - 0x7f7c8f770fff  ff3324bd2fda549672e01c2c966b0afc-le64.cache-4  ???
0x7fffd75f6000 - 0x7fffd75f7fff  linux-gate.so  ???

**Comment by zackw** [comment] 2015-10-14 14:08
Sorry for taking so long to get back to you about this.

Are you using PhantomJS 2.0?  1.9.x is no longer developed and has many crasher bugs.  If you're using 1.9.x please try to update to 2.0.

This stack trace, unfortunately, is useless, because it has no symbols, and because stack traces don't actuallly tell us much even when they have symbols.  If you still have the problem with 2.0, then what we need is a self-contained test case that demonstrates the problem.

Note also that nearly all crashes are bugs in Webkit.  We do not have the manpower to fix bugs in Webkit ourselves.  If you still have the problem with 2.0, then you are encouraged to try to reproduce it with nightly Webkit and report it to them (https://www.webkit.org/quality/reporting.html).

Because we can't to do anything more here than give you this advice, I am going to close this bug report now.  If you still have the problem with 2.0, and you have reason to believe it is *not* a Webkit bug, we ask that you file a new bug report including the self-contained test case (but not a stack trace).

**Closed by zackw** 2015-10-14 14:08 UTC
Labels: Bug, Crash, Need more information
