### ISSUE TITLE
Is 2.1.2 still prerelease?

### ISSUE THREAD

**Issue by ilovezfs** [ariya/phantomjs#15301] opened 2018-02-03 15:57 UTC
What is the latest stable version of this software?

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
Not running any version.
2. What steps will reproduce the problem?
  Go to https://github.com/ariya/phantomjs/releases
  Notice that 2.1.2 claims to be both pre-release and stable
  Get confused
3. Which operating system are you using?
macOS
4. Did you use binary PhantomJS or did you compile it from source?
Was thinking of updating the Homebrew formula from 2.1.1 -> 2.1.2 or 2.1.1 -> 2.1.3
5. Please provide any additional information below.
Thanks for your help.

**Comment by pixiuPL** [comment] 2018-02-04 14:24
@ilovezfs Latest stable will be next release version (2.1.4) that is going to be released in the first week of March (**if** everything will go as smooth as till today).

Current version is not stable, because it has one huge regression (see #15280)

**Comment by ilovezfs** [comment] 2018-02-04 14:26
@pixiuPL OK. You may want to edit https://github.com/ariya/phantomjs/releases/tag/2.1.2 then since it says "Stable, but minor release"

**Comment by pixiuPL** [comment] 2018-02-04 15:10
@ilovezfs Done.

Regarding release cycle (and other important things), please check [this page](http://phantomjs.org/anon) from time to time.

**Closed** 2018-02-04 15:11 UTC
