### ISSUE TITLE
please support web Worker

### ISSUE THREAD

**Issue by quaff** [ariya/phantomjs#10867] opened 2012-11-13 10:30 UTC
_**[zhouyanm...@gmail.com](http://code.google.com/u/118357786072020699366/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.7.0
> <b>What steps will reproduce the problem?</b>
1. new Worker('worker.js');
> <b>2.</b>
<b>3.</b>

> <b>What is the expected output? What do you see instead?</b>

> SECURITY_ERR: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
> <b>Which operating system are you using?</b>

> <b>Did you use binary PhantomJS or did you compile it from source?</b>
binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #867](http://code.google.com/p/phantomjs/issues/detail?id=867).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment] 2015-10-14 21:45
This might indicate that we have *regressed* on #10257 but it's not a duplicate.

I'm actually going to close this as a duplicate of #13653 because that one has a comprehensive test case.

**Closed by zackw** 2015-10-14 21:45 UTC
Labels: Bug, Confirmed, Duplicate
