### ISSUE TITLE
Crash with Mac OS X 10.10.3

### ISSUE THREAD

**Issue by fdubost** [ariya/phantomjs#13189] opened 2015-04-29 12:49 UTC
It seems that the compiled version for Mac OS X downloadable here http://phantomjs.org/download.html doesn't work with the last version of Yosemite (10.10.3) : impossible to run phantomjs command, it's killed immediately.

**Comment by ariya** [comment] 2015-04-29 23:43
Duplicate of #12900.

**Closed by ariya** 2015-04-29 23:43 UTC
