### ISSUE TITLE
pure virtual method called

### ISSUE THREAD

**Issue by GertGrossmann** [ariya/phantomjs#13182] opened 2015-04-27 13:02 UTC
We got a crash with PhantomJS 1.9.7. stack backtrace attached (rename .gif to .txt).

Regards, Gert

![phantomjs-1 9 7-trace txt](https://cloud.githubusercontent.com/assets/960803/7348020/23b599e4-ecee-11e4-9e7c-e54d0745f121.gif)

**Comment by sterol** [comment] 2015-11-10 14:48
Hello,
since opening this issue we didn't get a reply. The error appears to be more or less sporadic, however it occurs from time to time and we would like to find the cause. Any help very much appreciated.
In case you require more information pleas let us know.

Kind regards
Steffen

**Comment by zackw** [comment] 2015-11-10 16:38
We apologize for the delay in responding.

PhantomJS 1.x is no longer being developed.  It is very likely that this crash is resolved by 2.0, which contains a much newer version of Webkit.  We realize that you may be unable to upgrade at this time, however, we are not going to pursue this bug report further.

**Closed by zackw** 2015-11-10 16:38 UTC
Labels: 1.x, Bug, Crash

**Comment by sterol** [comment] 2015-11-10 17:07
I am very sorry, but I forgot to mention that we switched already to version 2.0. I will try to extract a new dump file if you still require this for further analysis. Please let me know. Or should I open a new issue?

**Comment by zackw** [comment] 2015-11-10 17:19
"Pure virtual method called" bugs are _always_ either Qt's fault or Webkit's fault (there aren't any pure virtual methods in PhantomJS proper) and we don't have the manpower to fix bugs in either of those ourselves.  However, we are willing to help you figure out which upstream project you should report the bug to.

Your first step should be to try to construct a minimal, self-contained test case that makes the crash happen _every time_.  I know that can be very difficult with this kind of bug, but only you can do it; we don't have enough access to your environment.  You might find `rr` helpful: http://rr-project.org/

Once you've got that, try to reproduce the problem with a nightly build of Webkit.  If it is, report it directly to them: https://www.webkit.org/quality/reporting.html  If it isn't, on the other hand, then we have to dig deeper, because it could be a Qt problem or a Qt/Webkit interaction or something even hairier, so then you file a *new* bug report with us, and provide the test case.  Please *don't* provide dumps, they tend to turn out to be useless.

**Comment by sterol** [comment] 2015-11-11 08:21
Thanks a lot. We will evaluate your proposal and decide on how we want to continue in this matter.
