### ISSUE TITLE
OS X binary does not work on Snow Leopard and Yosemite

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#12900] opened 2015-01-24 16:42 UTC
* Download the OS X binary of PhantomJS 2.0
* Run it on Snow Leopard
* PhantomJS refuses to run

**Comment by Vokkim** [comment] 2015-01-27 12:49
The [OS X binary](https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip) does not work in Yosemite (10.10.1) either, refuses to run and outputs `Killed: 9`.

**Comment by petermichaux** [comment] 2015-02-01 01:22
The OS X binary for PhantomJS 1.9.8 seems to work on Yosemite (10.10.1). The 2.0.0 binary does not work.

**Comment by eugene1g** [comment] 2015-02-01 13:27
@Vokkim @petermichaux  I had the same "Killed: 9" issue while starting Phantom2 on Yosemite, so I applied a small patch as recommended elsewhere (https://github.com/ariya/phantomjs/issues/12630#issuecomment-69337830) and recompiled working V2 binaries for OSX/Ubuntu/CentOS - they are available at https://github.com/eugene1g/phantomjs/releases if you want them

**Comment by jabez128** [comment] 2015-02-01 15:27
same issue +1

**Comment by steel** [comment] 2015-02-03 00:55
+1 here on Yosemite

**Comment by herrernst** [comment] 2015-02-12 13:51
From https://github.com/ariya/phantomjs/issues/12974: 
```
brew install upx
upx -d bin/phantomjs
```
Then it works.

**Comment by octatone** [comment] 2015-02-17 10:20
Broken here with any binaries I try on Yosemite.

**Comment by MichielDeMey** [comment] 2015-02-20 15:48
Exact same issue on OSX Yosemite.
```
[1]    57910 killed     ./phantomjs
```

**Comment by octatone** [comment] 2015-02-20 15:50
This is the only binary I could get to run on Yosemite: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip

**Comment by floriansemm** [comment] 2015-02-20 18:55
The solution from @herrernst works for me on Yosemite

**Comment by frameddialog** [comment] 2015-02-21 13:31
The solution from @herrernst works for me on Yosemite

**Comment by jackblackCH** [comment] 2015-02-24 16:10
The solution from @herrernst works for me on Yosemite

**Comment by sylvinus** [comment] 2015-03-01 22:08
Got the same on latest OS X 10.10.2

**Comment by milushov** [comment] 2015-03-03 09:35
thanks, @herrernst

**Comment by SpyderWeiss** [comment] 2015-03-07 00:08
I searched for 4 hours today to find this solution, this needs to be posted in a more prominent place, but thank you @herrernst !

**Comment by iRet** [comment] 2015-03-12 11:29
+1

**Comment by seanriordan** [comment] 2015-03-17 16:43
Thanks @herrernst

brew install upx
upx -d bin/phantomjs

**Comment by bartsmilner** [comment] 2015-03-18 19:02
Got the dreaded Killed: 9 with binary on Yosemite 10.10.2 but brew install phantomjs (on homebrew, natch) installed and worked no problem

**Comment by iabdulin** [comment] 2015-03-23 21:09
+1 for
```bash
brew install upx
upx -d bin/phantomjs
```

**Comment by mathiasbynens** [comment] 2015-03-23 21:11
This is fixed in master (3c3b47e7967ccaa1783d1329d4fa3a58ce06a00c). Let’s release v2.0.1 soon :)

**Comment by mathiasbynens** [comment] 2015-03-23 21:12
Nvm

**Comment by pyper** [comment] 2015-03-27 21:39
I think I found the issue.  I cd’d into the dirs for local storage and the cache, and cleared them out completely.  Once I did that no more problems.   Perhaps a file format change between versions.

In my case(OS X) they were here:

cd ~/Library/Caches/Ofi\ Labs/PhantomJS
rm -f -r data7

cd ~/Library/Application\ Support/Ofi\ Labs/PhantomJS
rm -f *.localstorage

**Comment by mathiasbynens** [comment] 2015-03-28 08:27
@pyper Confirmed. Thanks for the fix!

**Comment by sarbbottam** [comment] 2015-03-28 20:37
@pyper @mathiasbynens I could not get it working.

For my case, there was no (sub)directory for ``PhantomJS``  at ``~/Library/Caches/``, but ``~/Library/Application\ Support/Ofi\ Labs/PhantomJS``. Removed the ``*.localstorage``, but no luck.

**Comment by sarbbottam** [comment] 2015-03-28 20:48
@soda-wy's [solution](https://github.com/ariya/phantomjs/issues/12928#issuecomment-72457801) works perfectly for me.
>> the download link https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip on http://phantomjs.org/ failed with "Killed: 9".

>> https://github.com/eugene1g/phantomjs/releases works, thanks.

**Comment by rfanjul** [comment] 2015-04-08 11:47
@herrernst  also working for me thanks ! :)

**Comment by seanmac7577** [comment] 2015-04-10 20:12
The solution from @herrernst worked for me.

**Comment by kushG** [comment] 2015-04-15 15:49
Running it on Yosemite, but @herrernst solution doesn't works for me !

**Comment by Licas** [comment] 2015-04-15 22:24
@herrernst  solution worked for me too, thanks! (Mac OS X 10.10.3)

**Comment by herrernst** [comment] 2015-04-16 15:54
Just for the right credits, I got that from @wallneradam (via #12974).

**Comment by andrewmclagan** [comment] 2015-04-21 05:38
+1 upx installation worked on Yosemite

**Comment by bootstraponline** [comment] 2015-05-06 21:19
:+1:

**Comment by Sethathi** [comment] 2015-05-13 11:23
Thanks, @herrernst

**Comment by jonnolen** [comment] 2015-06-08 20:48
+1 upx installation worked on Yosemite

**Comment by sungwoncho** [comment] 2015-07-10 01:44
+1 for @herrernst's solution:

```
upx -d [path to phantomjs executable]
```

**Comment by a932455223** [comment] 2015-08-06 04:26
+1 from @herrernst 's solution.

**Comment by Vitallium** [comment] 2015-08-08 12:22
Looks like current master works well with upx now.

/cc @ariya

**Comment by dorayx** [comment] 2015-08-09 12:17
thanks, @herrernst

**Comment by montogeek** [comment] 2015-08-12 22:41
@herrernst didnt worked for me
```
montogeek ~/Downloads/phantomjs-2.0.0-macosx/bin [05:39 PM]→ 👾  💣  ./phantomjs --webdriver=4444
[ERROR - 2015-08-12T22:39:55.228Z] GhostDriver - main.fail - {"line":85,"sourceURL":":/ghostdriver/main.js","stack":"\tat global code (:/ghostdriver/main.js:85:56)"}

  :262 in error
```

**Comment by sebastianbochan** [comment] 2015-08-19 14:57
+1

**Comment by montogeek** [comment] 2015-08-19 15:03
My error was some process that didn't close correctly. After restarting the machine it worked.

**Comment by ScreenDriver** [comment] 2015-08-28 08:16
+1
The solution from @herrernst worked for me.

**Comment by oliver-moran** [comment] 2015-09-22 20:26
Just to pile on:
+1 Solution from @herrernst  works

**Comment by factologist** [comment] 2015-09-30 17:14
I used homebrew to update from 1.9.8 -> 2.0.0 which worked seamlessly on OSX 10.10.5.

`$ brew install phantomjs` (I was prompted to unlink the existing 1.9.8 -> `Error: phantomjs-1.9.8 already installed` followed by how-to instructions)

`$ brew unlink phantomjs` (successfully unlinked -> `Unlinking /usr/local/Cellar/phantomjs/1.9.8... 2 symlinks removed`)

`$ brew install phantomjs` and the install completed, version updated.

I had to mess with my required versions in my project's `Gemfile` and run bundler but that is to be expected.

**Comment by colinsauce** [comment] 2015-10-03 02:17
+1 @herrernst why can't this be fixed in the source?

**Comment by vml-rmott** [comment] 2015-10-08 19:16
if this is going to keep lingering, it should be posted as a known issue on the home page.

**Comment by Vitallium** [comment] 2015-10-08 19:17
https://github.com/ariya/phantomjs/issues/12900#issuecomment-128972972

**Comment by franksama** [comment] 2015-10-20 04:34
+1 @herrernst .. took me hours to figure this out, the upx solution worked for me.

**Comment by discorick** [comment] 2015-10-23 19:06
+1 @herrernst

**Comment by AbdullahAs** [comment] 2015-10-25 22:56
@soda-wy's solution works perfectly for me as well.

>the download link https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip on http://phantomjs.org/ failed with "Killed: 9".
>
>https://github.com/eugene1g/phantomjs/releases works, thanks.

**Comment by xiaoyongwu** [comment] 2015-10-28 21:57
"upx" solution worked for me on 10.10.5 Yosemite.

**Comment by jwalton** [comment] 2015-10-28 23:49
Why is phantomjs still broken on mac 9 months after this was reported???  :(

**Comment by sebastianbochan** [comment] 2015-10-29 13:30
Please check 2.0.1 version, which should fixed issues.

**Comment by lkraav** [comment] 2015-10-29 13:33
Is there supposed to be a 2.0.1 git tag/release? https://github.com/ariya/phantomjs/releases shows 2.0.0 for latest.

**Comment by MichielDeMey** [comment] 2015-10-29 16:49
2.0.1 is not released yet, check out the latest 2.0 branch.
That branch currently at 2.0.1-development.

**Comment by JordanTheriault** [comment] 2015-11-03 18:59
I was having the same problem.
@herrernst +1 for the solution, worked for me on 10.10.2

**Comment by danemacaulay** [comment] 2015-11-13 20:10
+1 for upx!

**Comment by Vitallium** [comment] 2015-12-12 12:54
Works now on OS X El Capitan.

**Closed by Vitallium** 2015-12-12 12:54 UTC
Labels: 2.0 Regression, Bug, Build system, MacOS X

**Comment by panxiubin** [comment] 2016-11-21 04:03
I have a same issue
[1]    48389 killed     phantomjs -v
