### ISSUE TITLE
Error when running v2.0.0 in Windows XP ( "phantomjs.exe is not a valid Win32 application")

### ISSUE THREAD

**Issue by justa9** [ariya/phantomjs#12992] opened 2015-02-13 14:49 UTC
I cannot seem to run phantomJS 2.0.0 under Windows XP.
An error window "phantomjs.exe is not a valid Win32 application" pops up and an "Access is denied." is being reported on the console (cmd.exe).

Version 1.9.7.0 (last installed) worked perfectly fine.

Any help?

**Comment by ariya** [comment] 2015-02-25 06:06
@Vitallium do you think it's a duplicate of another similar issue (I can't recall which)?

**Comment by Vitallium** [comment] 2015-02-26 16:03
@ariya I don't think so. I don't remember any similar issue.

**Comment by mjblue** [comment] 2015-02-26 16:13
We have the same issue on all our WIndows XP selenium runners, we upgraded to 2.0.0 from 1.9.8 and get this same error

**Comment by Vitallium** [comment] 2015-02-26 16:15
@mjblue can you run [Dependency Walker](http://www.dependencywalker.com/) on the executable file on any machine running Windows XP?

**Comment by mjblue** [comment] 2015-02-26 16:51
Hi @Vitallium Runnig Dependency Walker shows that MPR.DLL is failing to find MSJAVA.DLL
![depwalkerphantomjs2](https://cloud.githubusercontent.com/assets/6493461/6396670/a661cbb0-bdd7-11e4-8879-3e973a6bbe4c.jpg)

**Comment by Vitallium** [comment] 2015-02-26 17:07
Whoops..

http://blogs.msdn.com/b/vcblog/archive/2012/06/15/10320645.aspx

>The C++ runtime and libraries that accompany Visual Studio 2012 contain dependencies on several Windows API functions that exist only on Windows Vista and higher versions of the OS.  This means that applications built with Visual Studio 2012’s C++ compiler will fail to load and execute on Windows XP.

/cc @ariya @mjblue

**Comment by mjblue** [comment] 2015-02-26 17:21
ah yes.. from my olden days we had to keep an old machine with VS2010 just for this exact reason.. Is it possible to reassemble on VS2010 or are you removing XP support for the prebuilt binary?

**Comment by bharathirajap** [comment] 2015-03-11 08:40
we are using file version 1.9.7.0 and upgraded to 2.0 now its not working in windows 2003.

**Comment by ashkulz** [comment] 2015-03-13 05:15
I don't think Windows XP support is too important, but Windows 2003 is also broken due to this. You can [target XP/2003 using VS2012](http://blogs.msdn.com/b/vcblog/archive/2012/10/08/windows-xp-targeting-with-c-in-visual-studio-2012.aspx) but not VS2013 -- some fiddling is required. I use cross-compiled MinGW-w64 builds for targeting the old OS versions in [wkhtmltopdf](http://wkhtmltopdf.org/downloads.html#stable).

**Comment by KimBelanger** [comment] 2015-03-16 12:57
So does anyone has a binary thats currently working on Windows Server 2003 yet ?

**Comment by justa9** [comment] 2015-04-15 09:21
Do we have an update on this?

No sign of some love for WinXP or WinServer2003 users?

**Comment by ashkulz** [comment] 2015-04-15 12:03
Considering that Windows XP is not supported and Windows 2003 is over 12 years old, I don't think it is a priority for the developer team. You can try installing VS2010 Express and doing the compilation yourself if it is a blocker (after all, this is an open source project).

**Comment by ariya** [comment] 2016-01-08 04:50
XP can't run PhantomJS and Vista is specified as the minimum in the documentation.

**Closed by ariya** 2016-01-08 04:50 UTC

**Comment by xeoshow** [comment] 2016-03-03 07:17
Really a great pity that our target OS is winXP, so is there any workaround for making phantomjs work on winxp? Thanks so much!

**Comment by ariya** [comment] 2016-03-03 07:31
@xeoshow You can try to build it and compile it yourself.

**Comment by xeoshow** [comment] 2016-03-03 07:38
I tried the latest release and used the Dependency Walker , it tells IESHIMS.DLL and WER.DLL is missing, can I just find the 2 dll files and put it somewhere and then it works? This way seems simpler.

**Comment by xeoshow** [comment] 2016-03-03 09:08
Thanks for reply!

I am new to phantomjs, and sorry to ask if there is any wiki or link for how to build?

**Comment by Vitallium** [comment] 2016-03-03 09:09
@xeoshow if you need PhantomJS 2 for Windows XP you have to compile it by yourself from sources.

But remember you also need a special setup for it: http://doc.qt.io/qt-5/windows-issues.html
How to build PhantomJS: http://phantomjs.org/build.html

**Comment by xeoshow** [comment] 2016-03-03 09:13
@Vitallium Got it, thank you v much!

**Comment by xeoshow** [comment] 2016-04-23 06:54
Sorry still one more question: phantomjs 1.9.8 should support winxp out of the box? Thanks!

**Comment by Vitallium** [comment] 2016-04-23 08:10
@xeoshow yes, PhantomJS 1.9.8 supports Windows XP. But we don't support this version.

**Comment by xeoshow** [comment] 2016-04-27 03:37
Got it. Really a great pity that the newest version does not support winxp. Just tried 1.9.8 but seems some feature not supported.
How and where can I get the 2.1.2 to support winxp service? I tried to build it by myself but got various errors. I could pay for it personally ...
Great thanks!

**Comment by xeoshow** [comment] 2016-04-28 10:55
@ashkulz  By cross-compiled MinGW-w64 builds, do you mean you have the phantomjs 2.1.1 windows xp build? Could you please kindly help to share? Thanks a lot!

**Comment by ashkulz** [comment] 2016-04-28 11:00
@xeoshow: that's for wkhtmltopdf, a different project ... and it too doesn't support XP/2003 these days, though you can compile from source to get support.

**Comment by xeoshow** [comment] 2016-04-30 06:21
@ashkulz Thanks!

And below is from the build link, looks like some accurate info missing, such as the version of Perl, Python, Ruby, and Git, and which windows OS are OK for setup such build env? WinXP, windows 7 or 8, 32bit or 64bit?
Sorry for those newbie questions, but really need further help. Hopefully there could be some good documentaion for building targeted winxp since it is not supported out of the box ...

----------------------------
Windows requirements

Supported toolchains: MSVC2012 and MSVC2013.

You must have Perl, Python, Ruby, and Git on PATH. Also, note that Git comes with it’s own version of perl.exe. If you have both Git and a separate perl installation in your PATH, please make sure that you separate Perl install’s bin folder comes before the git’s bin folder in your PATH.

Please also add the folder \src\qt\3rdparty\gnuwin32\bin to your PATH, as required tools such as bison, flex, and gperf will not be found otherwise. Ex: ```SET PATH=%CD%\src\qt\3rdparty\gnuwin32\bin;%PATH%```

Run the build script from Visual Studio Command Prompt.

Tip: Enabling incremental linking will make the linkage process faster.

**Comment by icetision** [comment] 2017-07-09 18:13
@xeoshow, hello, are you compile 1.9.7 version for win XP?
