### ISSUE TITLE
Google Maps API TypeError: Unable to delete property

### ISSUE THREAD

**Issue by visnup** [ariya/phantomjs#12836] opened 2014-12-18 01:28 UTC
When using latest phantomjs 1.9.8, trying to load a web page that has a Google map results in a thrown TypeError with message "Unable to delete property". The stack trace (of minified code) is:

```
TypeError: Unable to delete property.
   :219
   https://maps.gstatic.com/maps-api-v3/api/js/19/4/main.js:20
   https://maps.gstatic.com/maps-api-v3/api/js/19/4/main.js:20
   https://maps.gstatic.com/maps-api-v3/api/js/19/4/main.js:19
   :218
   https://maps.gstatic.com/maps-api-v3/api/js/19/4/main.js:20
   https://maps.gstatic.com/maps-api-v3/api/js/19/4/main.js:20
   https://maps.gstatic.com/maps-api-v3/api/js/19/4/main.js:21
   :176
   :31
   https://maps.gstatic.com/maps-api-v3/api/js/19/4/main.js:26
   :178
```

As of Dec 16 and v3.18, this test case worked. Also, as of Dec 10 and v3.exp everything was fine too. It was only when patch releases on maps.gstatic.com were released that we started seeing these issues. I filed a [matching issue against Google Maps API][1] too.

A simplified test case is:

```javascript
var page = require('webpage').create();

page.onError = function(message, trace) {
  console.log(message);
  trace.forEach(function(item) {
    console.log('  ', item.file + ':' + item.line);
  })
}

var url = 'https://developers.google.com/maps/documentation/javascript/examples/map-simple';
page.open(url, function() {
  page.render('example.png');
  setTimeout(function() { phantom.exit() }, 3000);
});
```

[1]: https://code.google.com/p/gmaps-api-issues/issues/detail?id=7475&thanks=7475&ts=1418865703

**Comment by DouweM** [comment] 2015-01-05 14:18
I'm seeing the same error, which is preventing our tests on Circle CI from succeeding.

**Comment by 23tux** [comment] 2015-01-07 09:24
+1 Same error phantomjs 1.9.8 on Mac OS X 10.9.5

**Comment by 4lt4i** [comment] 2015-01-08 12:43
+1 same error with phantomjs 1.9.7.1 and osx 10.8.5

**Comment by iradul** [comment] 2015-01-08 14:42
With PhantomJS 2.0 this is working just fine.

**Comment by yaronel** [comment] 2015-01-09 19:30
I can confirm it works for me with PhantomJS 2.0 as well, though since it's not a stable release I am worried what other things might break.

You can download it from here:
https://github.com/bprodoehl/phantomjs/releases

**Comment by shahafabileah** [comment] 2015-01-17 01:17
Looks like I'm hitting the error too:

```
TypeError: Unable to delete property.
1
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 19 in bf
2
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 19 in bf
3
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 18 in [anonymous]
4
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 19 in bf
5
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 19 in bf
6
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 19 in bf
7
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 18 in [anonymous]
8
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 27 in [anonymous]
9
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 51 in [anonymous]
10
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 26 in ag
11
File https://maps.gstatic.com/maps-api-v3/api/js/18/20/main.js line 51 in [anonymous]
12
File https://<my-server>/<my-minified-code>.js line <whatever> in refreshMapMarkers
```

My code is making this call:
```
                // If there are 2+ markers, assume it's safe to use the bounds.
                map.fitBounds(bounds);
```

The error happened one time in our dev environment and got logged.  It might be PhantomJS-related (we use that for tests) or it might be Mac OSX related (all our dev machines or Macs).

**Comment by fiedl** [comment] 2015-01-24 01:14
Same error with OS X Yosemite 10.10.1 (14B25), ruby 2.1.2p95, phantomjs 1.9.8, poltergeist-1.5.0.

The error does *not* appear *on travis* for us.

**Comment by robd** [comment] 2015-01-26 17:09
Using the latest experimental version (v3.19), which includes a workaround, fixed this problem for me: https://code.google.com/p/gmaps-api-issues/issues/detail?id=7475#c20

**Comment by yulinwang** [comment] 2015-01-26 22:15
Yes, Google has provided the fix in version 3.19, but not released yet, so you have to specify version explicitly right now.
If using Google Map API, you can set version to 3.19 in URL to include the fix, like "https://maps.googleapis.com/maps/api/js?v=3.19"
But if using Google Charts API, there's no way to specify Google Map's version.
Finally we find a workaround to load both Google Map and Google Charts to specify the version.

      // specify google charts version
        google.load('visualization', '1',{
            'packages' : [ 'map' ],
            'callback': function() {
               // specify google map version here
                google.load('maps', '3.19', {
                    'callback' : drawMap
                });
            }
        });

Hope it helps.

**Comment by robd** [comment] 2015-02-17 17:28
Google maps 3.19, which fixes this problem (as discussed above) was released as the production version on the [17 Feb 2015](https://code.google.com/p/gmaps-api-issues/wiki/JavascriptMapsAPIv3Changelog), so I suggest that this issue could now be closed.

**Comment by JunichiIto** [comment] 2015-02-24 22:29
> I suggest that this issue could now be closed.

I agree. I confirmed "Unable to delete property" error fixed.

**Comment by ilife5** [comment] 2015-03-07 09:51
I also get this error when using phantom-limb

```
onError
{ '0': 'TypeError: Unable to delete property.',
  '1': 
   [ { file: 'http://localhost/kami-demo/src/vendor/phantom-limb.js',
       line: 114,
       function: '' } ] }

```

**Comment by ariya** [comment] 2016-01-24 04:48
The entire example script will be removed, we're not going to maintain such a fragile example script.

**Closed by ariya** 2016-01-24 04:48 UTC
