### ISSUE TITLE
Prebuilt 2.1.3 does not run on Debian Stretch (9.3)

### ISSUE THREAD

**Issue by interone-ms** [ariya/phantomjs#15311] opened 2018-02-07 12:04 UTC
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2.1.3 (downloaded from https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs)

2. What steps will reproduce the problem?
  1. Download phantomjs
  2. `chmod +x ./phantomjs`
  3. `./phantomjs`

3. Which operating system are you using?

Debian Stretch 9.3 x64, from Docker's `debian:stretch` image

4. Did you use binary PhantomJS or did you compile it from source?

Binary

5. Please provide any additional information below.

Output from ldd:
```
root@2d59f0a1674d:/# ldd ./phantomjs
	linux-vdso.so.1 (0x00007ffee8bac000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fda1c5be000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fda1c2b6000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fda1c078000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fda1bdc9000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
	libicui18n.so.55 => not found
	libicuuc.so.55 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fda1bbc5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fda1b9bd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fda1b7a0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fda1b41e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fda1b11a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fda1af03000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fda1ab64000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fda1c7d8000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fda1a93a000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fda1a707000)
root@2d59f0a1674d:/#
```

The reason for the problems are:

* Debian Stretch does not provide libssl 1.0.0, but ships with 1.1 and 1.0.2 only (per https://packages.debian.org/search?keywords=libssl&searchon=names&suite=stable&section=all)
* phantomjs forces a dependency on the not-by-default libraries libicu and libcrypto instead of being a fully self-contained static program. This should either be fixed or mentioned at the download page. By fixing it, #15310 could also be solved.

**Comment by pixiuPL** [comment] 2018-02-08 17:29
@interone-ms #15310 will **not** be fixed as long as original problem source have been found as its not PJS related issue. Many packages in Unix world has this issue. As soon as there is a **working** solution to this issue, it will be incorporated into PJS. You may count on me :) Since than - closing this.

**Closed by pixiuPL** 2018-02-08 17:29 UTC

**Comment by interone-ms** [comment] 2018-02-08 17:34
Hi @pixiuPL - the NPM package on https://www.npmjs.com/package/phantomjs-bin claims to have gathered the binaries from your official download page. If this is true, the 2.1.1 binary it ships does not depend on external libraries, and therefore I'd consider this bug report a regression report for 2.1.3 instead.

```
# md5sum phantomjs-bin-master/bin/linux/x64/phantomjs
3f4bbbe5acd45494d8e52941936235f2  phantomjs-bin-master/bin/linux/x64/phantomjs
# ldd phantomjs-bin-master/bin/linux/x64/phantomjs
	linux-vdso.so.1 (0x00007ffcc3dd9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0fb01b7000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f0faff79000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f0fafcca000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0fafac6000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0faf8be000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0faf6a1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0faf31f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0faf01b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0faee04000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0faea65000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0fb03d1000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f0fae83b000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f0fae608000)
```

**Comment by pixiuPL** [comment] 2018-02-08 17:42
@interone-ms Two things here::

1. 2.1.1 is tagged with **EOL** meaning **no** support is given,
2. Its not regression => I decided to abandon dynamic linking due to error in/with shared libs. New version (2.1.4) will be fully statically linked. Current version (2.1.3) has dynamic linking, but I strongly advice against using this version in production enviroments.

**Comment by interone-ms** [comment] 2018-02-08 17:43
Oh, cool, that's nice to hear. Do you have any ETA on when 2.1.4 will be available?

**Comment by pixiuPL** [comment] 2018-02-08 17:53
@interone-ms It **should** be available as public beta in mid-March

**Comment by ariya** [comment] 2018-03-06 03:04
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
