### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ivanoblomov** [ariya/phantomjs#13826] opened 2015-12-22 19:43 UTC
[7E95E9C0-3650-40D3-A4F1-5B7AFD3EF1E2.dmp.zip](https://github.com/ariya/phantomjs/files/70117/7E95E9C0-3650-40D3-A4F1-5B7AFD3EF1E2.dmp.zip)

**Comment by zackw** [comment] 2015-12-22 19:51
I regret to say that a crash dump all by itself is useless to us.  However, here is some advice.

* Are you using PhantomJS 2.0, or even better, the latest 2.1-beta builds?  These contain many, many crash fixes.  1.x is no longer being developed.
* To do anything at all about any bug, we need a complete, minimal, and self-contained test case.  This is the *smallest possible* set of files that can be used to reproduce the bug, plus precise instructions on how to go about it.  The ideal form is a script + web resources that can be added to our automated test suite.
* Nearly all crashes in PhantomJS are caused by bugs in WebKit, and we do not have the manpower to fix WebKit bugs ourselves.  If you can, investigate whether this crash is visible in a WebKit nightly build (see webkit.org) and if so, report it directly to them.

Since we cannot do anything with this bug report as is, I am going to close it.  Feel free to reopen if you can reproduce the problem with 2.0 and provide us a test case.

**Closed by zackw** 2015-12-22 19:51 UTC

**Comment by ivanoblomov** [comment] 2015-12-22 20:06
Thanks for the quick feedback. We're looking into 2.0 now.

Anyway, +1 on updating the warnings in 2.0 ;)
