### ISSUE TITLE
Memory Leak: Phantomjs 2 checked out on 13th November 2014

### ISSUE THREAD

**Issue by surenderthakran** [ariya/phantomjs#12903] opened 2015-01-25 05:06 UTC
Phantomjs version: Phantomjs 2 (built from source on 13th Nov 14 from master)

I wrote a script to scan websites using phantomjs. I open not more than 4 simultaneous pages at any point.
Some serious memory leak happens when i run it 

> page.settings.loadImages = false;

I run my script on an amazon linux ec2 server with a 1GB ram and a single core processor (its one of the lighter servers).

When not loading images my ram usage gradually increases to 99% as seen by the "top" command before phantom crashes.
However, when loading images it stabilizes at around 6-7%.

**Comment by alexey89777** [comment] 2015-01-25 06:56
+1 have the same issue too

**Comment by ariya** [comment] 2015-01-27 05:45
Can you build the tag `2.0.0` and try it again? If that still happens, I'll mark this as Regression.

**Comment by surenderthakran** [comment] 2015-01-27 11:44
@ariya ok will try again on 2.0.0

**Comment by iradul** [comment] 2015-01-31 04:51
+1

**Comment by iradul** [comment] 2015-02-03 18:31
This is WebKit related issue :
https://bugreports.qt.io/browse/QTBUG-34494 (https://codereview.qt-project.org/#/c/76934/)
https://bugreports.qt.io/browse/QTBUG-36530
https://bugreports.qt.io/browse/QTBUG-38857

Take a look at this test script, you'll see how memory usage grows up to 1GB with ```--load-images=false``` but with ```--load-images=true``` it doesn't grow more then 350MB:
```javascript
var page = require('webpage').create(),
	u = ["http://www.google.com/","https://www.facebook.com/","https://www.youtube.com/","https://www.yahoo.com/","http://www.amazon.com/","http://www.bing.com/","http://www.ebay.com/","http://www.wikipedia.org/","http://detroit.craigslist.org/","https://www.linkedin.com/","https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=12&ct=1422984414&rver=6.4.6456.0&wp=MBI_SSL_SHARED&wreply=https:%2F%2Fmail.live.com%2Fdefault.aspx%3Frru%3Dinbox&lc=1033&id=64855&mkt=en-us&cbcxt=mai","https://twitter.com/","https://accounts.google.com/ServiceLogin?service=blogger&passive=1209600&continue=https://www.blogger.com/home&followup=https://www.blogger.com/home&ltmpl=start","http://www.aol.com/","http://go.com/","https://www.pinterest.com/","http://www.msn.com/","https://www.tumblr.com/","http://www.cnn.com/","http://www.ask.com/","http://www.huffingtonpost.com/","https://www.netflix.com/us/","https://www.paypal.com/home","http://www.weather.com/","http://conduit.com/","http://espn.go.com/","http://instagram.com/","https://wordpress.com/","https://www.bankofamerica.com/","http://akamihd.net/","http://www.imdb.com/","https://www.chase.com/","http://www.microsoft.com/en-us/default.aspx","http://www.about.com/","http://www.avg.com/us-en/homepage","http://www.pornhub.com/","http://xfinity.comcast.net/tt2/?cid=BBI","http://www.foxnews.com/","http://www.apple.com/","http://www.walmart.com/","http://xhamster.com/","http://home.mywebsearch.com/index.jhtml","https://www.wellsfargo.com/","http://www.xvideos.com/","http://www.yelp.com/","http://imgur.com/","http://www.nytimes.com/","http://www.nbcnews.com/","http://www.cnet.com/","http://www.reddit.com/","http://www.adobe.com/","http://www.ehow.com/","http://www.pandora.com/","http://www.pch.com/","http://www.hulu.com/","http://www.zedo.com/","https://www.etsy.com/","https://www.flickr.com/","http://www.outbrain.com/","http://optmd.com/","http://www.indeed.com/","http://new.livejasmin.com/en/?showPreviousVersionLink=0","http://www.zillow.com/","http://www.target.com/","http://www.xnxx.com/","http://www.homedepot.com/","http://www.redtube.com/","http://www.answers.com/","http://www.att.com/","http://www.shopathome.com/","http://www.wikia.com/Wikia","http://www.dailymail.co.uk/ushome/index.html","https://www.usps.com/","http://www.babylon.com/","http://www.ups.com/","http://www.bestbuy.com/","http://www.youporn.com/","http://www.reference.com/","https://www.godaddy.com/","http://www.groupon.com/","http://www.deviantart.com/","http://www.usatoday.com/","http://www.pof.com/","https://www.capitalone.com/","http://www.bbc.co.uk/","http://www.washingtonpost.com/","http://www.match.com/","http://drudgereport.com/","http://mlb.mlb.com/home","http://www.tripadvisor.com/","http://www.pogo.com/","http://www.verizonwireless.com/","https://accounts.google.com/ServiceLogin?service=blogger&passive=1209600&continue=https://www.blogger.com/home&followup=https://www.blogger.com/home&ltmpl=start","http://www.buzzfeed.com/","http://doublepimp.com/Account/LogIn","http://inksr.com/","http://www.fedex.com/","http://inksdata.com/","http://www.aweber.com/","http://abcnews.go.com/","https://vimeo.com/","https://hootsuite.com/","http://bleacherreport.com/","http://www.lowes.com/","http://www.yellowpages.com/","https://www.americanexpress.com/","http://www.tube8.com/","https://www.salesforce.com/"]
	i = 0;
page.onError = function() {}
function open() {
	var url = u.shift();
	if (url) {
		page.open(url, function(x) { 
			console.log(i++ + ' : ' + url + ' : ' + x);
			setTimeout(open, 2000);
		});
	} else {
		phantom.exit();
	}
}
open();
```

**Comment by rubemz** [comment] 2015-06-13 20:33
+1 here, any thoughts on a fix for this this?

**Comment by hgati** [comment] 2015-06-14 07:39
+1 me too.

**Comment by dhruvbhatia** [comment] 2015-06-22 09:08
+1 same issue

**Comment by nomi-wei** [comment] 2015-06-28 06:23
+1 here

**Comment by behrangsa** [comment] 2015-07-21 23:32
Any ETAs for a fix for this issue?

**Comment by druxax** [comment] 2015-08-07 10:40
+1 please fix it

**Comment by manning23** [comment] 2015-09-14 06:45
+1 please fix it

**Comment by behrangsa** [comment] 2015-09-15 12:25
Guys, this is a QT bug it seems. If you want it fixed, please vote here: https://bugreports.qt.io/browse/QTBUG-38857

**Comment by Tomtomgo** [comment] 2015-09-15 13:14
Voted.

**Comment by mepard** [comment] 2015-09-26 12:05
Here's a workaround that was adequate for my purposes: set loadImages to true, then use onResourceRequested to abort requests for image urls. In my case, I'm using casper.on('resource.requested'). It seems to stop the leaks without other side effects.

**Comment by brovikov** [comment] 2015-10-10 04:52
@behrangsa voted

**Comment by ZhiweiWang** [comment] 2015-11-10 05:39
@mepard good idea!

**Comment by maZahaca** [comment] 2015-11-13 14:41
+1 to fix it

**Comment by maZahaca** [comment] 2015-11-13 14:42
@mepard I'm getting error: TypeError: Object #<Object> has no method 'abort'
on attempt to abort request. PhantomJS 2.0.

**Comment by mepard** [comment] 2015-11-16 19:20
This is working for me (OS X 10.11 and Windows 10):

```javascript
function ResourceRequested (request, networkRequest)
{
	if (options.workAroundLoadImagesLeak)
	{
		// Work around memory leak in WebKitQT in PhantomJS 2.0.0 when not loading images.
		// In initialize above we told PhantomJS to always load images, but here we'll suppress
		// the image resources.
		if (/\.(jpg|jpeg|png|gif|tif|tiff|mov)$/i.test(request.url))
		{
			if (options.trackResources)
			{
				console.log(moment().format() + ': Suppressing image #' + request.id + ': ' + request.url);
			}
			networkRequest.abort();
			return;
		}
	}
}
```

**Comment by mepard** [comment] 2016-01-20 21:58
FWIW, https://codereview.qt-project.org/#/c/76934/2 claims to have fixed this, but it doesn't seem like it to me. The master branch currently has the change, but the leak still happens.

**Comment by behrangsa** [comment] 2016-01-21 08:45
@mepard The bug is still open: https://bugreports.qt.io/browse/QTBUG-38857

**Comment by mepard** [comment] 2016-01-28 21:41
Turns out it's a WebKit bug. I suspect it's the same as https://bugs.webkit.org/show_bug.cgi?id=17469 even though that report doesn't mention autoLoadImages.

**Comment by firexp** [comment] 2016-02-23 15:32
+1

**Comment by mepard** [comment] 2016-02-25 15:47
I just did a run where I visited around 330 pages with lots of images. Without this patch memory consumption hit around 2.5 GB, with the patch it was about 500 MB.

**Comment by coderzbx** [comment] 2016-04-21 10:21
set option:load_image as True, resolve my problem

**Comment by tolark** [comment] 2016-05-02 22:58
well, after 3 years it isn't still fixed. This issue is for all operating systems not only for windows. I tried on osx el capitan, windows 10 and ubuntu, in all operating systems I have been facing memory leak issue when I tried to disable images in all ways.

**Comment by tolark** [comment] 2016-05-03 01:28
It has been 3 years without any fixes. 2.1.1 has still memory leak issue in all operating systems.

**Comment by behrangsa** [comment] 2016-05-08 08:19
I appreciate that this is an open source project, but if you were an end user of your own project and had to eat your own dog's food, would you be happy with such an important bug to be left unfixed for three years?

At least start a campaign, ask for an amount of donation that you think would be enough to fix this problem, ask people to contribute and donate money, and then focus on this issue and fix it.

Goddamit ;) https://youtu.be/0ubcetW9-D8?t=4s

**Comment by javenosa** [comment] 2016-05-09 18:55
+1 fix please!

**Comment by psellers89** [comment] 2016-07-14 23:18
+1 ...

**Comment by volvofixthis** [comment] 2016-07-25 23:03
+1

**Comment by Chort409** [comment] 2016-08-01 22:54
+1

**Comment by onedesert** [comment] 2016-08-23 13:14
+1

**Comment by behrangsa** [comment] 2016-08-24 01:53
...20 years later: +1

**Comment by maZahaca** [comment] 2016-08-24 04:08
ahaha, yeah! old guys are still pressing the button "+1"

**Comment by psychok7** [comment] 2016-08-30 23:25
+1

**Comment by xmiao** [comment] 2016-09-22 07:20
+1

**Comment by max-favilli** [comment] 2016-10-29 12:11
+1

**Comment by blueboxapps** [comment] 2016-10-31 17:25
+1

**Comment by arkkanoid** [comment] 2016-11-07 21:17
+1

**Comment by tjkz87** [comment] 2016-11-08 05:27
+1

**Comment by toldroyd** [comment] 2016-11-08 18:47
+1

**Comment by dvygolov** [comment] 2016-11-10 11:15
+1

**Comment by matthewstifler** [comment] 2016-11-12 21:14
+1 (please)

**Comment by anexplore** [comment] 2016-12-02 07:28
+1 please!!

**Comment by Rosefox911** [comment] 2017-01-10 18:57
+1 Please, this is still an issue 1 year later. :(

**Comment by grigoriy-didorenko** [comment] 2017-01-26 14:41
+1

**Comment by Vitallium** [comment] 2017-02-07 12:48
Let's track this in https://github.com/ariya/phantomjs/issues/11390

**Closed by Vitallium** 2017-02-07 12:48 UTC
Labels: old.Regression

**Comment by threematesarl** [comment] 2017-05-03 15:37
+1

**Comment by ChasingRainbows** [comment] 2017-09-09 09:52
+1
