### ISSUE TITLE
viewportSize causes crash - 2.0 & Master

### ISSUE THREAD

**Issue by BenjaminLeeMiller** [ariya/phantomjs#13201] opened 2015-05-04 19:52 UTC
I am just learning phantomJS so it is possible I am missing something and this isn't a real bug, but it seems to be.

I am following the instructions for taking a screenshot and wanted to change the viewportSize so that I could get the a screenshot that was more representative of the actual page as a user sees it.  Here is the code I am using:

> var page = require('webpage').create();
> page.viewportSize = {width: 800, height: 800};
> page.open('https://www.ruby-lang.org/en/documentation', function(status) {
>   console.log("Status: " + status);
>   if(status === "success") {
>     page.render('ruby.png');
>   }
>   phantom.exit();
> });

When I execute this script, i get:

> Status: success
> Assertion failed: (_consumed <= scratch_size), function _hb_coretext_shape, file src/hb-coretext.cc, line 764.
> Abort trap: 6

I have tried building 2.0 from source, master from source, and brew installing PhantomJS.  All produce the same result.

One interesting fact, if I drop the viewportSize to 400 x 400 or remove it, I instead get
> libpng error: Read Error

Additionally, if I change the url to "https://www.ruby-lang.org/", the code runs without error, but no image gets generated.

This same code works fine if I switch the url to some other site such as http://www.askart.com/AskART/artists/search/Search_Repeat.aspx?searchtype=AUCTION_RECORDS&artist=111780

**Comment by Vitallium** [comment] 2015-05-06 19:22
Duplicate of #12918.

**Closed by Vitallium** 2015-05-06 19:22 UTC
