### ISSUE TITLE
Crash OS X

### ISSUE THREAD

**Issue by sglaser** [ariya/phantomjs#13852] opened 2016-01-02 18:44 UTC
I was getting an infinite set of

`2016-01-02 12:11:05.758 phantomjs[79145:2596879] Critical failure: the LastResort font is unavailable.` 

In an effort to debug this, I started commenting out stuff in my html file. I commented out a bunch of &lt;img&gt; and the problem went away. As I was uncommenting them, individually to locate the culprit, I got a dump instead.

These &lt;img&gt; tags are in one chapter of a large document (~1500 pages when printed). I have no problem producing any individual chapter without commenting out anything so it's clearly something related to size or interactions between chapters.

OS X 10.11.2 (latest version), PhantomJS installed from Homebrew (latest version).
[79CA43C1-22FB-404D-88FA-3CEA2D3BF86A.dmp.zip](https://github.com/ariya/phantomjs/files/76351/79CA43C1-22FB-404D-88FA-3CEA2D3BF86A.dmp.zip)

I tried running this again and was not able to reproduce the crash. The LastResort stuff is very reproducible.

I tried building from source with the latest commit. No change in behavior (though I had trouble building qtbase so I'm not sure I trust that build -- build claimed it couldn't detect the system architecture).

**Comment by zackw** [comment] 2016-01-02 19:05
This is two different bugs, and I'm very sorry to say that *both* of them are almost certainly bugs in Webkit and we do not have the manpower to fix Webkit bugs ourselves.

What you need to do is work up two *different* minimal test cases, one for the LastResort stuff and one for the crash, and then see if they exhibit the same problems in a Webkit nightly build.  You're on OSX, so this is easy: binaries are downloadable from http://nightly.webkit.org/.  If the bugs do reproduce in a Webkit nightly build, please report them directly to the Webkit developers: see https://webkit.org/reporting-bugs/ for instructions. 

On the other hand, if they *don't* reproduce in Webkit nightlies, then we would like to see your minimal test case for the LastResort issue *only*; you may assume that the crash will be fixed by a future import of Webkit (we do not backport individual fixes for the same manpower reasons).

FYI, crash dumps are almost always useless to us and trunk builds have stopped producing them.

I'm going to close this bug report now because we can't do anything with it as is, but if you determine that the LastResort issue happens in PhantomJS but not in nightly Webkit, please reopen it when you provide us the test case.

**Closed by zackw** 2016-01-02 19:05 UTC
Labels: 2.0, Bug, Webkit

**Comment by sglaser** [comment] 2016-01-02 21:27
Thanks. I'll try WebKit in a bit and report back. 

The <img> tags were including SVG files generated by Adobe Illustrator. They use different fonts than the main text so that might be the culprit. 

Steveg

**Comment by sglaser** [comment] 2016-01-04 15:27
I can’t reproduce it on webkit. Tried using Revision 194284 was built on December 18, 2015.

Just to make sure I was doing it right:

1. Run webkit app
2. It runs Safari pointing to the updated webkit instead of the built in version (Safari 9.0.2 if it matters).
3. Page loads properly
4. I used the UI of the page to save an HTML version of the page (ReSpec button -> Save Snapshot -> Save as HTML)

This produces a new tab with the output (as it does on Safari). Doing the same thing on Firefox saves the result in ~/Downloads/index.html. It used to work on Chrome, but for some reason the Save as HTML doesn’t do anything.

I wasn’t able to figure out how to use the JavaScript code I run on phantomjs to work with webkit.app. Is that possible without rebuilding phantomjs?


Steve Glaser
sglaser@sglaser.com
