### ISSUE TITLE
PhantomJs Version 2.0 has issue which was not in Version 1.9

### ISSUE THREAD

**Issue by AbhijitMuke** [ariya/phantomjs#12990] opened 2015-02-13 06:13 UTC
PhantomJs  version 2.0 has issue which version 1.9 don't have.There must be something I am missing or may changes happen in version 2.0 .Please check Following Observation,

Please find file here - https://www.dropbox.com/sh/lh0ljqw8rxo3gm7/AABQqPJoLRnb5w-nn6tTt3o9a?dl=0
 
Command - "phantomjs.exe rasterize.js test.html output.pdf"

HTML file to test - test.html

PhantomJs version 1.9.7 result - v_1.9.pdf

PhantomJs version 2.0.0 result -  v_2.0.pdf

So, I observe extra width in version 2.0 while converting html to pdf .Please let me now which changes should I do to resolve this issue in PhantomJS 2.0.Thanks.

**Comment by AbhijitMuke** [comment] 2015-02-13 06:42
Try with copying rasterize.js file from version 1.9 into version 2.0 ...still running in same problem...

**Comment by DerekDomino** [comment] 2015-02-13 14:59
I have similar issue too: in version 2.0.0, rendered font sizes and picture sizes are reduced compared to version 1.9.7.

Does the default unit changed between both version?

**Comment by thomasbachem** [comment] 2015-02-22 11:22
This is a duplicate of #12685

**Comment by ariya** [comment] 2015-02-23 13:44
Closing as duplicate.

**Closed by ariya** 2015-02-23 13:44 UTC
