### ISSUE TITLE
ReferenceError: Can't find variable: Promise

### ISSUE THREAD

**Issue by liliakai** [ariya/phantomjs#12401] opened 2014-07-25 16:42 UTC
I'm using mocha-phantomjs 3.5.0 (phantomjs 1.9.7). My mocha tests pass in Chrome but phantom gives the error above.

:ghost:

**Comment by zzarcon** [comment] 2015-01-05 15:42
@JamesMGreene some update about this? :)

**Comment by zzarcon** [comment] 2015-01-05 15:55
I ended using a simple workaround; adding this [Promise Polyfill](https://github.com/taylorhakes/promise-polyfill/blob/master/Promise.js) at the beginning of the tests, hope be util for you!

**Comment by JamesMGreene** [comment] 2015-01-05 17:02
Although the current `master` isn't quite where we hoped it would be, we are planning to release it as `v2.0.0` on January 23rd (?) and work out the remaining kinks from there once we can all shift focus to `v2 x`.

**Comment by JamesMGreene** [comment] 2015-01-05 17:05
That said: I have **not** verified that the native `Promise` API is implemented in `master`.

**Comment by Vitallium** [comment] 2015-01-05 17:08
PhantomJS 2 doesn't have support for native `Promise` API.

**Comment by fredck** [comment] 2015-02-20 11:46
+1 

[Promise is available natively in all modern browsers](http://caniuse.com/#feat=promises) except IEs (IE12 has it)... it's a must have!

**Comment by MrJH** [comment] 2015-02-25 09:13
+1

**Comment by masi** [comment] 2015-03-21 14:03
Node has Promise and notably SilmerJS it too. The devs had the idea to make webpage.open to return a Promise which is IMHO a great improvement to the API.

**Comment by mockdeep** [comment] 2015-06-19 17:06
Just ran into this. I'll give the polyfill a try.

**Comment by masi** [comment] 2015-06-20 08:13
Shims (polyfills) for promises work well.

**Comment by danawoodman** [comment] 2015-07-24 20:03
Any progress on this?

**Comment by kawing-chiu** [comment] 2015-07-26 06:10
Using es6-promise polyfill works for me. But the promise must be put into the page's js code, not to the phantomjs script.

**Comment by dbaba** [comment] 2015-09-30 07:51
+1
[es6-promise](https://github.com/jakearchibald/es6-promise) works for me as well as polyfill though (PhantomJS 2.0.0).

**Comment by hbrysiewicz** [comment] 2015-12-15 00:47
+1

**Comment by jimmywarting** [comment] 2016-01-28 20:52
+1

**Comment by dteleguin** [comment] 2016-02-09 21:22
+1

**Comment by floverdevel** [comment] 2016-02-10 12:56
We had the same problem and choose to inject Babel into our test suite for now.
Our unit tests runs on node.js with jasmine and are therefor ok with Promise.
But our cucumber tests runs into phantom.js and we injected Babel libray to polyfill Promise.

https://babeljs.io/ works great, but maybe to have «native support» of ES6 feature would even better :)

**Comment by jimmywarting** [comment] 2016-02-10 14:34
@floverdevel That is what i have been doing. Would agree that it would be cool to have native support. but there is things that not even a precompiler can solve... like if the website i'm navigate to uses arrow function, generators and what not.
That is why i'm considering switching to SlimerJS to use an up to date Gecko browser. Seems to me that phantomjs is falling behind on the webkits release cycle's :-1: 

Would love phantomjs if it used Blinks engine and had auto update as well. Having to wait for a third party to update their product and update is dependency is urck.
It's like this with samsung phones. Just buy Google's Nexa phone and you know you will be the first to receive an update. Don't have to wait for samsung to wait for next android version so they can update the consumer's phone 3-8 month later or even at all.

**Comment by floverdevel** [comment] 2016-02-10 18:28
@jimmywarting i love the comparison with Samsung and the Android update :P

**Comment by sickDevelopers** [comment] 2016-02-12 15:52
+1

**Comment by msn0** [comment] 2016-02-27 12:58
+1

**Comment by rafaelhz** [comment] 2016-03-07 20:32
+1

**Comment by jasmith79** [comment] 2016-03-09 18:11
+1

**Comment by Jezternz** [comment] 2016-03-10 03:53
+1

**Comment by inaccessible** [comment] 2016-03-23 20:46
+1

**Comment by AChris07** [comment] 2016-03-31 22:06
+1

**Comment by sygn** [comment] 2016-04-01 09:43
+1

**Comment by msn0** [comment] 2016-04-01 11:24
+1

**Comment by Radiergummi** [comment] 2016-04-05 12:38
+1

**Comment by jimmywarting** [comment] 2016-04-05 14:02
Can you stop writing +1 so we don't get useless notifications all the time
Github have introduced reactions. use that instead.

<img width="165" alt="screen shot 2016-04-05 at 15 59 06" src="https://cloud.githubusercontent.com/assets/1148376/14284366/8b7bb230-fb47-11e5-9a27-b952e6a1a07a.png">

**Comment by nmors** [comment] 2016-04-13 08:25
Running into this issue also. including https://raw.githubusercontent.com/stefanpenner/es6-promise/master/dist/es6-promise.min.js does the job. Would be great to support es6 in pjs though..

**Comment by SourceCode** [comment] 2016-04-22 20:31
I have an open issue on StackOverflow regarding promise support and CasperJS.  We ended up moving to SlimerJS until the support for native promises is added to phantomJS.  The issue is here:   http://stackoverflow.com/questions/36603470/casperjs-phantomjs-es6-promise-polyfill for others facing this same issue.  No resolution has been posted on how to handle this in the client and I was unable to inject anything into phantom that would handle the support for whatever reason.  If someone has a resolution it would be greatly appreciated otherwise I look forward to the native promise support in Phantom when it becomes available.  Thank you for the hard work!

**Comment by Lacerda** [comment] 2016-06-17 10:04
Either [es6-promise](https://github.com/stefanpenner/es6-promise) and [promise-polyfill](https://github.com/taylorhakes/promise-polyfill) do the trick! 
Thank you @dbaba, @zzarcon and @kawing-chiu for the suggestions!

Just need to include one of them in karma.conf.js in [`files` option](http://karma-runner.github.io/0.13/config/files.html)

es6-promise:
`files: ['./node_modules/es6-promise/dist/es6-promise.js']`

promise-polyfill:
`files: ['./node_modules/promise-polyfill/promise.js']`

**Comment by ariya** [comment] 2016-08-25 14:02
Please track ES6 support in #14506. Thank you!

**Closed by ariya** 2016-08-25 14:02 UTC
Labels: Webkit

**Comment by baipgydx729** [comment] 2016-09-07 04:12
+1

**Comment by NeilJ247** [comment] 2017-01-03 12:37
@dbaba how did you go about adding the Promise polyfill?  Are you adding it to original source webpage or injecting it somehow using PhantomJS?

Thanks in advance.

**Comment by Zoheb-hassan** [comment] 2017-07-20 07:02
There's a phantomjs polyfill that can downloaded via the npm manager, [`https://www.npmjs.com/package/phantomjs-polyfill`](link) this helps resolve the promise error you will encounter

**Comment by kid-wumeng** [comment] 2017-09-22 13:22
@Zoheb-hassan the page of https://github.com/ariya/phantomjs/issues/link is 404

**Comment by Somebi** [comment] 2017-09-24 13:03
+1 :D Get ES6 support faster ffs.

**Comment by annelledj** [comment] 2017-11-06 10:32
The following in karma.conf.js did not work for me
`files: ['./node_modules/es6-promise/dist/es6-promise.js']`

I had to change it to this to get it to work :)
`files: ['./node_modules/es6-promise/dist/es6-promise.auto.js']`
