### ISSUE TITLE
PhantomJS 2.0 does not work in Mac OS Yosemite

### ISSUE THREAD

**Issue by peterchenkai** [ariya/phantomjs#12928] opened 2015-02-01 13:03 UTC
PhantomJS 2.0 does not work in Mac OS Yosemite.  It failed with "Killed: 9".

**Comment by eugene1g** [comment] 2015-02-01 13:45
Related to #12900 and #12630

I'm not affiliated with the project, but I encountered the same issue so I recompiled a working binary at https://github.com/eugene1g/phantomjs/releases if you want it.

**Comment by soda-wy** [comment] 2015-02-02 13:30
the download link https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip on http://phantomjs.org/ is failed with "Killed: 9".

https://github.com/eugene1g/phantomjs/releases  is works, thanks.

**Comment by rdpanek** [comment] 2015-02-02 13:34
I have the same problem. I must build Phantomjs 2.0 from repository,  ~30min and CPU on max

**Comment by ariya** [comment] 2015-02-02 17:53
Duplicate of #12900.

**Closed by ariya** 2015-02-02 17:53 UTC

**Comment by raycursif** [comment] 2015-02-16 07:46
I have the same issue

**Comment by jackblackCH** [comment] 2015-02-24 16:07
+1 same here

**Comment by tofias** [comment] 2015-02-26 00:01
Yup.
