### ISSUE TITLE
Webfonts don't work in Windows version

### ISSUE THREAD

**Issue by iangilman** [ariya/phantomjs#13541] opened 2015-08-31 23:37 UTC
Hello! I've just discovered webfonts don't work in 2.0.0 on Windows. I understand that might be part of 2.0.1? Any word on that release? If I can't wait, what are my options? Presumably I can try building from the master on the repo? Are there nightly builds or something I could grab? 

Thank you for your help!

**Comment by Vitallium** [comment] 2015-09-01 07:37
Yes, it will be in 2.0.1 release. To enable web fonts you need to compile PhantomJS with zlib.

**Comment by iangilman** [comment] 2015-09-01 17:40
Great to hear! I assume I follow the instructions in the Windows section of http://phantomjs.org/build.html (but without the `git checkout 2.0`). How do I enable zlib? 

Also, do you know if the build will work with https://www.visualstudio.com/products/visual-studio-community-vs ? The build page says 2012/2013, but it looks like the latest is 2015. 

Of course if anyone here already has a built Windows version of Phantom with webfonts they can point to, I'd love to hear about it!

**Comment by zadahead** [comment] 2015-09-06 01:25
hey, 
i have the same issue.

how did you enabled zlib (on windows platform) 
and did it fix this issue?

thanks

**Comment by iangilman** [comment] 2015-09-09 16:23
@zadahead Unfortunately we still haven't figured that out...we'll let you know if/when we do; please do the same!

**Comment by iangilman** [comment] 2015-09-09 16:28
@zadahead Looks like this comment from @Vitallium covers it: 

https://github.com/ariya/phantomjs/issues/10592#issuecomment-104670467

**Comment by yairza** [comment] 2015-09-14 18:00
Does Anyone got a build to share with the world and save humanity?

**Comment by iangilman** [comment] 2015-09-14 21:51
@yairza I ended up giving up and went with a Mac based server instead. That said, I'm still interested if someone comes up with a Windows build!

**Comment by astefanutti** [comment] 2015-09-14 22:02
@yairza @zadahead you may want to try the version maintained for [DeckTape](https://github.com/astefanutti/decktape) which are available at https://github.com/astefanutti/decktape/tree/gh-pages/downloads.

**Comment by yairza** [comment] 2015-09-16 08:39
@astefanutti thanks! however it seems that the windows version is still not supporting web fonts, or am i missing something?

**Comment by astefanutti** [comment] 2015-09-16 17:25
@yairza I haven't dig that much into your issue though I've managed to export HTML presentations with Web fonts correctly on Windows OS with the provided executable from DeckTape. One example is http://mikemaccana.github.io/rejectjs2013/ exported into https://astefanutti.github.io/decktape/examples/new-es5-overloards.pdf.

Other examples of presentations with Web fonts exported on Windows OS can be found here: https://github.com/astefanutti/decktape#examples.

That being said, that may be a completely different use case than yours.

**Comment by ariya** [comment] 2016-01-26 06:45
Can you try it again with PhantomJS 2.1?

**Comment by rlaytham** [comment] 2016-02-09 18:11
It appears that WOFF fonts still aren't rendered on Windows in PhantomJS 2.1.1.  PhantomJS 1.9 is able to render both of the WOFF fonts I tested.

**Comment by Vitallium** [comment] 2016-02-09 18:17
@rlaytham sample?

**Comment by rlaytham** [comment] 2016-02-09 18:38
Try extracting the contents of this zip file to a folder and running "phantomjs.exe renderpng.js".  The font is rendered in PhantomJS 1.9 (and in Chrome), but not in 2.1.1.  

The zip file also includes screen captures generated from PhantomJS 1.9 and 2.1.1.
[render_woff.zip](https://github.com/ariya/phantomjs/files/123582/render_woff.zip)

**Comment by Vitallium** [comment] 2016-02-09 18:46
Indeed. Confirmed. Thanks for reporting! This will be fixed in the next patch release!

**Comment by rlaytham** [comment] 2016-02-09 18:47
Fantastic.  Thank you for the quick response.

**Comment by Vitallium** [comment] 2016-02-09 18:49
For developers: looks like QtWebkit tries to find the dynamic version of the zlib library. But we use static version. I already a have fix for this. Will push it shortly.

**Comment by bigheadzen** [comment] 2016-02-23 08:19
Any progress of patch? I've met same issue. Thanks a lot.

**Comment by chrisber** [comment] 2016-03-22 11:06
@Vitallium  where can we find the patch?

**Comment by vietnh** [comment] 2016-03-30 04:58
I'm facing the same issues version 2.1.1 on Windows doesn't support webfonts. Is there any built in version which I can use?

**Comment by jacksodj** [comment] 2016-04-28 19:31
any update on this? is there a patch available?

**Comment by chrisber** [comment] 2016-04-28 19:52
Workaround for me was to use wkhtmltopdf directly instead of the phantomjs wrapper.
The fix for the issue is described here: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1527#issuecomment-72549818
and take a note of this post:
http://blog.gluga.com/2012/05/wkhtmltopdf-font-and-sizing-issues.html

**Comment by Vitallium** [comment] 2016-04-28 19:53
This issue should be fixed in `master` branch.

**Comment by Vitallium** [comment] 2016-04-30 08:51
Fixed in `master`

**Closed** 2016-04-30 08:51 UTC
Labels: 2.1 Regression, Bug, In progress, Patch available, Windows

**Comment by phawxby** [comment] 2017-02-14 14:38
Is this fix going to be released soon? It has been a year since the last update

**Comment by Rukenshia** [comment] 2017-04-11 16:26
This still doesn't seem to work @Vitallium ?

**Comment by Vitallium** [comment] 2017-04-11 16:27
@Rukenshia 2.5 version can render Web fonts

**Comment by jacksodj** [comment] 2017-04-11 16:37
where is version 2.5? I only see 2.1.1

**Comment by Vitallium** [comment] 2017-04-11 16:37
Here - https://bitbucket.org/ariya/phantomjs/downloads But it's in the beta phase atm.

**Comment by phawxby** [comment] 2017-04-11 18:49
Any idea how long this will be in beta. It has been a year since the last stable release.

**Comment by IAMtheIAM** [comment] 2017-08-29 19:13
Any update? Since april no activity?

**Comment by phawxby** [comment] 2017-08-29 19:30
PhantomCSS and PhantomJS are essentially dead now GoogleChrome/puppeteer and Nightmarejs have come along. 

The former uses the actual latest version of chrome so features arrive quickly.

**Comment by IAMtheIAM** [comment] 2017-08-30 16:07
@phawxby Wow this is awesome, thanks for informing me of these new tools. JS community evolves fast :-)

**Comment by IAMtheIAM** [comment] 2017-08-30 16:07
They seem to do very similar things, which is better suited for PDF rendering of a page, if you are familiar?

**Comment by MichaelKorn** [comment] 2017-11-28 11:06
Unfortunately, GoogleChrome/puppeteer does not support custom Header/Footer:
https://productforums.google.com/forum/#!topic/chrome/N7XsmwYV15U

**Comment by ronkot** [comment] 2018-03-23 13:39
@MichaelKorn Puppeteer seems to support custom header and footer now: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions

**Comment by MichaelKorn** [comment] 2018-03-25 13:24
@ronkot Thanks, we are using custom header and footer in Puppeteer since last week. It is working fine and we will replace phantomjs completely.
