### ISSUE TITLE
Can't download binary files using curl / wget

### ISSUE THREAD

**Issue by icy** [ariya/phantomjs#14212] opened 2016-04-19 08:28 UTC
The download page https://bitbucket.org/ariya/phantomjs/downloads is now protected by some mechanism, and that breaks all Docker builds that use `wget/curl` to download phantomjs binary.

Please allow us to download binary files from your page. We are working from the Linux shell, and *we are not human*!

**Comment by thuandt** [comment] 2016-04-19 08:36
How about change `User-Agent`, maybe it can help you :)

**Comment by icy** [comment] 2016-04-19 08:38
@thuandt  I tried and it didn't help at all :(

**Comment by icy** [comment] 2016-04-19 09:26
The links seems to work now (I didn't change anything on my client).

Let's see if that happens again.

Thanks!

**Comment by ariya** [comment] 2016-06-07 12:08
Duplicate of #13953.

**Closed by ariya** 2016-06-07 12:08 UTC
