### ISSUE TITLE
Screen Capture : phantomjs-2.0.0 does not  convert webpage to png/jpg  correctly 

### ISSUE THREAD

**Issue by jagadale1** [ariya/phantomjs#13145] opened 2015-04-10 13:45 UTC

**Comment by jagadale1** [comment] 2015-04-10 14:01
I am using phantomjs-2.0.0-windows to convert wepage file to jpg file. For some file it generate image with black color background. I am using following cmd
phantomjs.exe rasterize.js "index.html" output.jpg 1920px. 

I have output File and view of input file. Pleas help me.

![output](https://cloud.githubusercontent.com/assets/6037512/7089211/d70670d4-dfb7-11e4-923d-9ce9f52c2947.jpg)
![actul_view_webpage](https://cloud.githubusercontent.com/assets/6037512/7089251/1dac28a8-dfb8-11e4-9b1e-5ecd70d0d79d.png)

**Comment by Vitallium** [comment] 2015-04-10 14:04
@jagadale1 you can change the background by evaluating the following code before you call `render`:
````
page.evaluate(function() {
    document.body.bgColor = 'white';
});
````
Check out our [FAQ](http://phantomjs.org/faq.html)

**Comment by jagadale1** [comment] 2015-04-10 14:31
thank you very much for reply. I have add this code but got following Issue 
TypeError: null is not an object (evaluating 'document.body.bgColor =  'white'')
  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3

**Comment by DPr00f** [comment] 2015-04-13 16:43
try document.body.style.backgroundColor = 'white'

**Comment by jagadale1** [comment] 2015-04-16 13:13
I have mention issue details  on 
http://stackoverflow.com/questions/29563612/phantomjs-2-0-0-does-not-convert-webpage-to-png-jpg-correctly

**Comment by zackw** [comment] 2015-04-24 14:21
Thank you for the bug report.  Is there any chance you can provide us with a self-contained, minimal HTML page that shows the issue?  Also, note that PhantomJS does not and probably never will support Flash objects.

**Comment by ryanohoro** [comment] 2015-09-10 21:58
Same as this issue, for which I posted a workaround:

https://github.com/ariya/phantomjs/issues/12724#issuecomment-139381271

**Comment by zackw** [comment] 2015-12-22 00:35
Yeah, duplicate of #12724.  Thanks for finding that, @ryanohoro.

**Closed by zackw** 2015-12-22 00:35 UTC
Labels: Bug, Need minimized test case, Need more information, Webkit
