### ISSUE TITLE
Problems starting a new session

### ISSUE THREAD

**Issue by paromo** [ariya/phantomjs#13599] opened 2015-09-22 10:02 UTC
Hi,

we have randomly occurring problem with starting a new session:

Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'sx508', ip: '172.16.66.14', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-4-amd64', java.version: '1.7.0_55'
Driver info: driver.version: PhantomJSDriver

org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'sx508', ip: '172.16.66.14', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-4-amd64', java.version: '1.7.0_55'
Driver info: driver.version: PhantomJSDriver
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:130)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:79)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:168)
	at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.execute(PhantomJSCommandExecutor.java:78)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:115)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:104)
	at de.idealo.security.smoketests.selenium.SeleniumHelper.createPhantomDriver(SeleniumHelper.java:64)
	at de.idealo.security.smoketests.selenium.SeleniumHelper.createPhantomDriver(SeleniumHelper.java:75)
	at de.idealo.security.smoketests.selenium.SeleniumHelperTest.testCreatePhantomDriver_0args(SeleniumHelperTest.java:56)

I have attached in this ticket the crash dump file.
Note! The attached file actually a textfile, which I created according to these instructions:
http://phantomjs.org/crash-reporting.html

however the issue reporting tool seems to support only images :)

Best regards,
![dump_textfile](https://cloud.githubusercontent.com/assets/5600862/10015621/bd2dc6bc-6121-11e5-9b28-541f74b67cd3.png)

Pasi Romo

**Comment by zackw** [comment] 2015-10-12 20:30
I'm sorry for the delay getting back to you about this.

This appears to be a crash in the C library, probably due to memory corruption.  There are several possible explanations for this, and unfortunately, we can't help you very much with any of them.

* Make sure you are using PhantomJS 2.0.  1.9.x is no longer supported and is known to have many crasher bugs that are fixed in 2.0.

* Try to construct the smallest possible test case that makes the bug happen *consistently* rather than intermittently.  Try to avoid the use of Selenium/WebDriver.

* Your computer's RAM may be faulty - no, I'm not joking.  Commodity-grade RAM is notorious for dropping bits under heavy load.  It is also possible that you don't have enough of it.  I bring this up because you say the problem is intermittent.  If you can't construct a test case that makes the bug happen *every single time*, try swapping in a beefier computer (ideally, one with ECC RAM) and see if that makes the problem go away.

* If you still have the problem with PhantomJS 2.0 and you can construct a test case that makes it happen every single time, the next thing to try is whether it's reproducible in a nightly build of Webkit.  If it is, report it to the Webkit developers -- we don't have the manpower to fix their bugs ourselves.

* If you *can* make the problem happen every single time, in 2.0, but not in Webkit, and it doesn't look like the problem is one that would be resolved by upgrading Webkit, only then we would like to see the test case.

**Comment by paromo** [comment] 2015-10-14 12:10
Hi,

thank you for your detailed response. We are running the tests on 64-bit linux and since it doesn't seem yet to be available an official 2.0 version we built it from source but ended up with this error while running the tests:

error while loading shared libraries: libicudata.so.52: cannot open shared object file: No such file or directory

I tried to run the tests on two different environments:
* Linux jenkins-java-08 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux
* Linux ls20903 3.2.0-58-generic #88-Ubuntu SMP Tue Dec 3 17:37:58 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

with the same problem. There seems to be another lengthy discussion related to similar kind of problem:
https://github.com/ariya/phantomjs/issues/12948

Should I gather from this that 2.0.0 is not yet usable on linux?

Best regards,
Pasi

**Comment by zackw** [comment] 2015-10-14 13:25
Thanks for being willing to attempt to compile 2.0 from source.  It does work on Linux, but you need to install more library packages than were required for 1.9.x. On Debian and Ubuntu, run this command as root:

    apt-get install build-essential g++ libexpat1-dev libfontconfig1-dev libfreetype6-dev \
                          libicu-dev libjpeg62-turbo-dev libpng12-dev libssl-dev zlib1g-dev

and then recompile phantomjs *on that system*.

**Comment by paromo** [comment] 2015-10-14 17:02
Thank you very much for your quick reply. I tried running the tests with a binary built on the same system and indeed this solved the problem. We will now continue running the tests based on your previous recommendations.

Best regards,
Pasi

**Closed** 2015-10-14 17:23 UTC
Labels: Bug, Crash, Fixed in 2.0, Webdriver API
