### ISSUE TITLE
phantomjs 2 fails to render pdf properly

### ISSUE THREAD

**Issue by athibaud** [ariya/phantomjs#12936] opened 2015-02-02 14:48 UTC
i'm on osx 10.9.5 using a built version from a2912c216d06df4d8b51f12ad4082a48c5fc7ba6

i'm trying to render html to an A5 portrait pdf but i never get the required result. the pages do not respect css `width` and `height`.

[here](https://gist.github.com/athibaud/c7bd4809baaf5cc11e19)'s my rasterize script, a simplified version of [that](https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js) one.
and here is an [html test file](https://gist.github.com/athibaud/5d8d49e329b1f1d261aa) (it's got two A5 portrait pages, first is blue, second is red)

so when is go ahead and `phantomjs rasterize.js test.html test.pdf` i get 
![phantomjs2fail](https://cloud.githubusercontent.com/assets/1503735/6001757/4514d55c-aaed-11e4-8e36-c4f2b18ddd58.png) 

whereas with `phantomjs1` i get the correct
![phantomjs1success](https://cloud.githubusercontent.com/assets/1503735/6001764/5a5227a8-aaed-11e4-9c7a-008d587442a5.png) (the white lines being osx preview artifacts probably due to rounding millimeters to pixels)

i've tried messing around with all the parameters (`pageSize`, `clipRect`, `viewportSize`, `zoomFactor`..) to no avail :(

**Comment by TheCloudlessSky** [comment] 2015-02-03 19:19
:+1:

**Comment by polarathene** [comment] 2015-02-05 11:20
@athibaud Can you share a screenshot with a render of one of the colours set at half width? PhantomJS 2 renders PDF differently on Windows, previously it was broken, the 2.0.0 update is far more accurate. I tried your html on Windows with 2.0.0 and most likely due to rounding it is 1px short in width, and 1px over in height. This can be worked around by providing width/height in the css in px instead 560px wide, 793px tall. I got the initial px values by multiplying the physical inch sizes by the DPI, on windows that is 96, it might be 72 for OSX I think. From my experiments units are all converted to px where 96px in css is equivalent to 1 inch. Let me know if the values I gave you work, else try these if Phantom is scaling by 72 instead of 96. 419px wide, 595px tall(You might need to adjust slightly as either could be over/under A5 width). Also from what I've seen you might have a typo in your css width mm units, width appears to be 148mm for A5 not 158mm.

@TheCloudlessSky What version of PhantomJS are you using? A newer build of 2.0.0 was released since, try it here: https://bitbucket.org/ariya/phantomjs/downloads

**Comment by athibaud** [comment] 2015-02-05 14:44
@polarathene thank you for your comment

> I tried your html on Windows with 2.0.0 and most likely due to rounding it is 1px short in width, and 1px over in height. This can be worked around by providing width/height in the css in px instead 560px wide, 793px tall. I got the initial px values by multiplying the physical inch sizes by the DPI, on windows that is 96, it might be 72 for OSX I think. 

i went ahead and used pxs in my css.. its worked out well for now so i'll use that a quickfix.
i don't have much time to understand/investigate why using mms doesn't work though, i wish i could look into it more..

> From my experiments units are all converted to px where 96px in css is equivalent to 1 inch.

[precisely](https://github.com/ariya/phantomjs/blob/master/src/qt/qtwebkit/Source/WebCore/css/CSSHelper.h#L32) :)

> Also from what I've seen you might have a typo in your css width mm units, width appears to be 148mm for A5 not 158mm.

indeed there was a type hehe thanks for pointing it out.

so there is a problem with css "absolute" unit rendering in phantomjs. hope someone can fix it...

**Comment by TheCloudlessSky** [comment] 2015-02-05 15:11
@polarathene I just used the updated one and we're still experiencing the same problem. When we have PNG rendering, everything is nice and crisp as expected. When we do PDF rendering (same code), it is scaled in correctly.

For example, here is the PNG:

![image](https://cloud.githubusercontent.com/assets/613788/6062619/2436b308-ad1f-11e4-88bf-217258913a6d.png)

And here is the PDF (zoomed at 100%):

![image](https://cloud.githubusercontent.com/assets/613788/6062627/3396bcb2-ad1f-11e4-8a6a-36088e8e5ffd.png)

You can see that the PDF has extra whitespace and the text/blue shapes are scaled incorrectly.

**Comment by polarathene** [comment] 2015-02-05 15:25
@athibaud Can you please confirm which px settings worked for you? If I understand right it would have been 419px by 595px which is the px settings for 72 DPI. If that is the case the absolute unit thing isn't something that can be 'fixed' because it isn't broken. I believe other units like pt and mm are being converted to their px values, eg 1 inch will be converted to 96px, 1mm will get its equivalent too which is 3.779....px 148mm roughly rounds to 559px.

So how to come up with the 419px by 595px? I use this site as guide for inch values: http://www.a5papersize.org/ , and then multiply those by dpi(96 for Windows, 72 for OSX/Linux). Values seem to be getting scaled prior to rendering to PDF, all pt/mm/cm/etc are converted to px units, and all px units are scaled. % units don't seem to change though, I don't know what's going on behind scenes, perhaps PhantomJS is controlling this or QTWebkit plays role, I haven't looked into it. 

Super technical if you want more understanding: The data is then scaled back to paperSize, which seems to be 96 DPI for me on windows. In 1.9.8 I noticed my A4 PDF is 794px wide at 100% which is A4 at 96 DPI. However if paperSize is given pixels instead of value `A4` then it turns out I need to give 992px width, which still becomes 794px width at 100% on the PDF. 992px width is 120 DPI A4, browsers display at 96 DPI though I think, so my data was still being scaled down even if 992px element is given, it becomes 794px on PDF at 100%, user have to zoom in to see it same size as browser. 2.0 release all these problems on windows is gone, seems now OSX have them(But 72 DPI not 96)?

**Comment by polarathene** [comment] 2015-02-05 15:30
@TheCloudlessSky Are you sure that is using 2.0? How are you sending your data to Phantom? If it's using the PATH environment variable on your OS it might be using an older version of Phantom on your system somewhere. If you're using a nodeJS module, swap out the exe in the lib folder. The old one was about 7mb the new one is around 47mb.

If all that is good, what paperSize are you using? If you'd like me to test the example on my system provide a link and I'll make sure the error is still on 2.0. It looks very much like the scaling issue I was having on 1.9.8, same amount of whitespace on the right.

**Comment by athibaud** [comment] 2015-02-05 16:33
@polarathene 
> Can you please confirm which px settings worked for you? If I understand right it would have been 419px by 595px which is the px settings for 72 DPI.

yes, i used 420x595px

> Values seem to be getting scaled prior to rendering to PDF, all pt/mm/cm/etc are converted to px units, and all px units are scaled. % units don't seem to change though, I don't know what's going on behind scenes, perhaps PhantomJS is controlling this or QTWebkit plays role, I haven't looked into it.

hum. it would be nice to know for sure. hope the maintainers can enlighten us on that.

> Super technical if you want more understanding: The data is then scaled back to paperSize, which seems to be 96 DPI for me on windows. In 1.9.8 I noticed my A4 PDF is 794px wide at 100% which is A4 at 96 DPI. However if paperSize is given pixels instead of value A4 then it turns out I need to give 992px width, which still becomes 794px width at 100% on the PDF. 992px width is 120 DPI A4, browsers display at 96 DPI though I think, so my data was still being scaled down even if 992px element is given, it becomes 794px on PDF at 100%, user have to zoom in to see it same size as browser. 2.0 release all these problems on windows is gone, seems now OSX have them(But 72 DPI not 96)?

yes this sounds about right. you must have gone through a lot to figure all this out. i feel your pain :0

thank you very much for all the info though! its certainly very helpful and saves us a lot of time! so thank you again :)

now i'm trying all this out locally on osx but our servers run on linux so i have so see if there is the same issue there hehe, do you know??

**Comment by polarathene** [comment] 2015-02-05 17:02
No sorry I haven't gotten to testing on linux or osx yet, and yes haha spent 2-3 days looking into just this problem based on what I could find on the net and trial and error :) then when I have a solution for 1.9.8 finally, 30 mins later working windows 2.0.0 binary come out :P

@ariya Can you provide anymore information on this? It doesn't appear to be in the docs. It seems it was a problem for windows users with 1.9.8 with 120 dpi to 96 dpi and now it is 72 to 96 dpi for OSX/Linux users?

**Comment by TheCloudlessSky** [comment] 2015-02-05 19:39
@polarathene The `paperSize` is the same as the `viewportSize`:

```javascript
page.viewportSize = {
  width: dimensions.width,
  height: dimensions.height
};
// For PDF.
page.paperSize = {
width: dimensions.width + 'px',
  height: dimensions.height + 'px',
  margin: '0px'
};
```

**Comment by polarathene** [comment] 2015-02-06 02:43
@TheCloudlessSky On 1.9.8 you could sort of use a ratio of 1:1 and have accurate sizes at 125% PDF zoom. Honestly seemed like a bug and that has been fixed in 2.0.0. You just have to be aware of how paperSize changed, apply this to your paperSize calculation `(dimensions.width * (72/96)) + 'px'` add the same for height. If you want to understand why, the technical research I did below might help explain. Let us know if the solution works on your end please :)

I've just done some thorough testing of 2.0.0 PDF conversions and noticed the paperSize 'A4' definition that was 992px wide(120dpi) in 1.9.8 is now 595px wide(72dpi) in 2.0.0. Previously in 1.9.8 your unit values other than % had were scaled down, so that the PDF version required you to zoom to 125% to view units at their original size, also caused the whitespace issue on the right present in your picture due to that scaling. In 2.0.0 units don't appear to be scaled down, they are 100% matching to the browser. paperSize however is now scaling up from it's given px size by 1/3rd, this is matching it to 96dpi/96px per 1 inch which is a CSS inch. Thus 72DPI 595px A4 paperSize is resized to 794px 96DPI A4 when rendered. I've also learnt from OSX(and likely Linux) users that 1.9.8 provided 100% match for their PDF renders but with 2.0.0 they're having to downscale their units from 96dpi to 72dpi, eg 794px wide element needs to be changed to 595px for correct 100% zoom A4 PDF, for comparision on 1.9.8 with windows users that meant changing from 96dpi to 120dpi, 794px wide element needed to be 992px wide. Also worth noting is that between both versions % units would still remain precise, 90% element would always be 90% of the PDF at 100% zoom, for whatever reason they were not scaled like other units. Using zoomFactor in my experience is not recommended, I can't recall with 1.9.8 though I know it had similar problems, zoomFactor does not scale font or css sizes from what I can see, it was having an effect though as clientWidth/offsetWidth/innerWidth/etc were reporting to be scaled accordingly. I used Highcharts to create a svg chart in a 100% width div. Unlike elements being sized with % units like mentioned above, presumably jQuery got the width of the 100% wide div at that scale setting a px width(zoomFactor of 1.25 on 794px wide became 636px), in addition to that the alignment of text vertically was off in the svg rangeSelector component.

**Comment by TheCloudlessSky** [comment] 2015-02-06 19:28
@polarathene That worked for 2.0.0 - hopefully that can be fixed! What's the best approach for fixing it in 1.9.8 (since I'm using the NPM module)?

**Comment by polarathene** [comment] 2015-02-07 01:00
@TheCloudlessSky For windows on 1.9.8 the solution that worked for me was to apply `-webkit-transform: scale(2); -webkit-transform-origin: 0% 0%; width:50%` to the body tag of the html document. That wouldn't work for all sites though, mine was rather basic. You also had to provide 120dpi viewPort (eg 992px wide instead of 96DPI 794px)and 120DPI paperSize(If A4, you can just use A4, or it's pixel values 992px wide, 1400px tall) I think. Might have to double the viewPort dimensions as well can't remember. It basically upscaled  your CSS so it'd look correct at 100% zoom instead of 125% on the PDF, if you had any % units the body 50% made sure to halve them due to the doubling. This was just a snippet taken from someones script I came across during my research, I think it was called pixelRatio.js but was designed for .png only and was breaking my scripts.

**Comment by 9point6** [comment] 2015-02-19 17:01
Hi, I'm having similar issues which I can't seem to remedy, is there a way to force pre-2.0 behaviour for the DPI?

**Comment by polarathene** [comment] 2015-02-20 13:51
@9point6 Operating System? I know it's alot to read but I'm pretty sure I gave solutions for both windows and linux/mac. If you were on windows, pre 2.0 was broken, can't see why you'd want to restore that so I'm assuming mac. You'll need someone who knows the codebase better such as @ariya . Otherwise you have to calculate the dpi conversion like described above.

**Comment by 9point6** [comment] 2015-02-20 14:29
@polarathene It's on a Linux VM (but I believe it's the same issues as mac). Weirdly I've tried the solutions above and they don't seem to work. Possibly this is due to us not working any of the measurements for this out in pixels in the first place. All the CSS specifies everything in millimetres.

**Comment by polarathene** [comment] 2015-02-22 02:57
@9point6 millimetres will still be converted to 96px per inch I think as per CSS spec, you won't actually get physical mm measurement. And then due to the update I think you'll have that value converted to 72 dpi as an inch is 72px then. If you can alter the internal dpi linux uses to 96, you'd probably have a workaround, else you need to recalculate. If you use any values in % those don't appear to be converted to px.

**Comment by thomasbachem** [comment] 2015-02-22 11:24
This seems to be a duplicate of #12685

**Comment by Vitallium** [comment] 2015-05-14 21:59
Duplicate of #12685

**Closed by Vitallium** 2015-05-14 21:59 UTC
Labels: 2.0 Regression, Bug, Confirmed, Fixed in dev
